var __defProp = Object.defineProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// src/app.ts
import express3 from "express";
import { toNodeHandler } from "better-auth/node";
import cors from "cors";

// src/modules/menuItem/menuItem.router.ts
import express from "express";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.5.0",
  "engineVersion": "280c870be64f457428992c43c1f6d557fab6e29e",
  "activeProvider": "postgresql",
  "inlineSchema": 'model User {\n  id            String    @id\n  name          String\n  email         String\n  emailVerified Boolean   @default(false)\n  image         String?\n  createdAt     DateTime  @default(now())\n  updatedAt     DateTime  @updatedAt\n  sessions      Session[]\n  accounts      Account[]\n\n  role   Role    @default(CUSTOMER)\n  phone  String?\n  status String? @default("ACTIVE")\n\n  businessName String?\n  isApproved   Boolean @default(true)\n\n  addresses String?\n\n  cart Cart?\n\n  orders      Order[]      @relation("CustomerOrders")\n  reviews     Review[]\n  restaurants Restaurant[]\n\n  @@unique([email])\n  @@map("user")\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n  userId    String\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@unique([token])\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n\nenum Role {\n  CUSTOMER\n  PROVIDER\n  ADMIN\n}\n\nmodel Cart {\n  id String @id @default(cuid())\n\n  userId String @unique\n  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  items Json\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n\nmodel MenuItem {\n  id           String     @id @default(cuid())\n  restaurantId String\n  restaurant   Restaurant @relation(fields: [restaurantId], references: [id], onDelete: Cascade)\n\n  name        String\n  description String?\n  priceCents  Int\n  imageUrl    String?\n  isAvailable Boolean @default(true)\n\n  cuisine CuisineType\n\n  orders  Order[]\n  reviews Review[]\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([restaurantId])\n}\n\nenum CuisineType {\n  MEAT\n  FISH\n  VEG\n  VEGAN\n}\n\nmodel Order {\n  id         String @id @default(cuid())\n  customerId String\n  customer   User   @relation("CustomerOrders", fields: [customerId], references: [id], onDelete: Restrict)\n\n  menuItemId String\n  menuItem   MenuItem @relation(fields: [menuItemId], references: [id], onDelete: Restrict)\n\n  restaurantId String\n  restaurant   Restaurant @relation(fields: [restaurantId], references: [id], onDelete: Restrict)\n\n  status                  OrderStatus @default(PENDING)\n  totalCents              Int\n  notes                   String?\n  deliveryAddressSnapshot Json? // store address snapshot at time of order\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([customerId])\n  @@index([restaurantId])\n  @@index([menuItemId])\n}\n\nenum OrderStatus {\n  PENDING\n  CONFIRMED\n  PREPARING\n  OUT_FOR_DELIVERY\n  DELIVERED\n  CANCELLED\n}\n\nmodel Restaurant {\n  id String @id @default(cuid())\n\n  providerId String\n  provider   User   @relation(fields: [providerId], references: [id], onDelete: Cascade)\n\n  name        String\n  description String?\n  phone       String?\n  addressLine String\n  city        String\n  isActive    Boolean @default(true)\n\n  menuItems MenuItem[]\n  orders    Order[]\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@index([providerId])\n}\n\nmodel Review {\n  id     String @id @default(cuid())\n  userId String\n  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  menuItemId String\n  menuItem   MenuItem @relation(fields: [menuItemId], references: [id], onDelete: Cascade)\n\n  rating  Int // validate 1..5 in API layer\n  comment String?\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@unique([userId, menuItemId]) // one review per item per user\n  @@index([menuItemId])\n}\n\n// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"image","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"role","kind":"enum","type":"Role"},{"name":"phone","kind":"scalar","type":"String"},{"name":"status","kind":"scalar","type":"String"},{"name":"businessName","kind":"scalar","type":"String"},{"name":"isApproved","kind":"scalar","type":"Boolean"},{"name":"addresses","kind":"scalar","type":"String"},{"name":"cart","kind":"object","type":"Cart","relationName":"CartToUser"},{"name":"orders","kind":"object","type":"Order","relationName":"CustomerOrders"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToUser"},{"name":"restaurants","kind":"object","type":"Restaurant","relationName":"RestaurantToUser"}],"dbName":"user"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"},"Cart":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"CartToUser"},{"name":"items","kind":"scalar","type":"Json"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"MenuItem":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"restaurantId","kind":"scalar","type":"String"},{"name":"restaurant","kind":"object","type":"Restaurant","relationName":"MenuItemToRestaurant"},{"name":"name","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"priceCents","kind":"scalar","type":"Int"},{"name":"imageUrl","kind":"scalar","type":"String"},{"name":"isAvailable","kind":"scalar","type":"Boolean"},{"name":"cuisine","kind":"enum","type":"CuisineType"},{"name":"orders","kind":"object","type":"Order","relationName":"MenuItemToOrder"},{"name":"reviews","kind":"object","type":"Review","relationName":"MenuItemToReview"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Order":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"customerId","kind":"scalar","type":"String"},{"name":"customer","kind":"object","type":"User","relationName":"CustomerOrders"},{"name":"menuItemId","kind":"scalar","type":"String"},{"name":"menuItem","kind":"object","type":"MenuItem","relationName":"MenuItemToOrder"},{"name":"restaurantId","kind":"scalar","type":"String"},{"name":"restaurant","kind":"object","type":"Restaurant","relationName":"OrderToRestaurant"},{"name":"status","kind":"enum","type":"OrderStatus"},{"name":"totalCents","kind":"scalar","type":"Int"},{"name":"notes","kind":"scalar","type":"String"},{"name":"deliveryAddressSnapshot","kind":"scalar","type":"Json"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Restaurant":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"provider","kind":"object","type":"User","relationName":"RestaurantToUser"},{"name":"name","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"phone","kind":"scalar","type":"String"},{"name":"addressLine","kind":"scalar","type":"String"},{"name":"city","kind":"scalar","type":"String"},{"name":"isActive","kind":"scalar","type":"Boolean"},{"name":"menuItems","kind":"object","type":"MenuItem","relationName":"MenuItemToRestaurant"},{"name":"orders","kind":"object","type":"Order","relationName":"OrderToRestaurant"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"ReviewToUser"},{"name":"menuItemId","kind":"scalar","type":"String"},{"name":"menuItem","kind":"object","type":"MenuItem","relationName":"MenuItemToReview"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","user","sessions","accounts","cart","customer","provider","menuItems","orders","_count","restaurant","menuItem","reviews","restaurants","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","Cart.findUnique","Cart.findUniqueOrThrow","Cart.findFirst","Cart.findFirstOrThrow","Cart.findMany","Cart.createOne","Cart.createMany","Cart.createManyAndReturn","Cart.updateOne","Cart.updateMany","Cart.updateManyAndReturn","Cart.upsertOne","Cart.deleteOne","Cart.deleteMany","Cart.groupBy","Cart.aggregate","MenuItem.findUnique","MenuItem.findUniqueOrThrow","MenuItem.findFirst","MenuItem.findFirstOrThrow","MenuItem.findMany","MenuItem.createOne","MenuItem.createMany","MenuItem.createManyAndReturn","MenuItem.updateOne","MenuItem.updateMany","MenuItem.updateManyAndReturn","MenuItem.upsertOne","MenuItem.deleteOne","MenuItem.deleteMany","_avg","_sum","MenuItem.groupBy","MenuItem.aggregate","Order.findUnique","Order.findUniqueOrThrow","Order.findFirst","Order.findFirstOrThrow","Order.findMany","Order.createOne","Order.createMany","Order.createManyAndReturn","Order.updateOne","Order.updateMany","Order.updateManyAndReturn","Order.upsertOne","Order.deleteOne","Order.deleteMany","Order.groupBy","Order.aggregate","Restaurant.findUnique","Restaurant.findUniqueOrThrow","Restaurant.findFirst","Restaurant.findFirstOrThrow","Restaurant.findMany","Restaurant.createOne","Restaurant.createMany","Restaurant.createManyAndReturn","Restaurant.updateOne","Restaurant.updateMany","Restaurant.updateManyAndReturn","Restaurant.upsertOne","Restaurant.deleteOne","Restaurant.deleteMany","Restaurant.groupBy","Restaurant.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","AND","OR","NOT","id","userId","menuItemId","rating","comment","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","providerId","name","description","phone","addressLine","city","isActive","customerId","restaurantId","OrderStatus","status","totalCents","notes","deliveryAddressSnapshot","string_contains","string_starts_with","string_ends_with","array_starts_with","array_ends_with","array_contains","priceCents","imageUrl","isAvailable","CuisineType","cuisine","items","identifier","value","expiresAt","accountId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","email","emailVerified","image","Role","role","businessName","isApproved","addresses","every","some","none","userId_menuItemId","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "vQRSkAEWBAAAqQIAIAUAAKoCACAGAACrAgAgCgAArAIAIA4AAK0CACAPAACuAgAgqAEAAKUCADCpAQAAKgAQqgEAAKUCADCrAQEAAAABsAFAAJcCACGxAUAAlwIAIb4BAQCbAgAhwAEBAKcCACHHAQEApwIAIeUBAQAAAAHmASAApgIAIecBAQCnAgAh6QEAAKgC6QEi6gEBAKcCACHrASAApgIAIewBAQCnAgAhAQAAAAEAIAwDAACYAgAgqAEAAL0CADCpAQAAAwAQqgEAAL0CADCrAQEAmwIAIawBAQCbAgAhsAFAAJcCACGxAUAAlwIAIdkBQACXAgAh4gEBAJsCACHjAQEApwIAIeQBAQCnAgAhAwMAAKADACDjAQAAvgIAIOQBAAC-AgAgDAMAAJgCACCoAQAAvQIAMKkBAAADABCqAQAAvQIAMKsBAQAAAAGsAQEAmwIAIbABQACXAgAhsQFAAJcCACHZAUAAlwIAIeIBAQAAAAHjAQEApwIAIeQBAQCnAgAhAwAAAAMAIAEAAAQAMAIAAAUAIBEDAACYAgAgqAEAALsCADCpAQAABwAQqgEAALsCADCrAQEAmwIAIawBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb0BAQCbAgAh2gEBAJsCACHbAQEApwIAIdwBAQCnAgAh3QEBAKcCACHeAUAAvAIAId8BQAC8AgAh4AEBAKcCACHhAQEApwIAIQgDAACgAwAg2wEAAL4CACDcAQAAvgIAIN0BAAC-AgAg3gEAAL4CACDfAQAAvgIAIOABAAC-AgAg4QEAAL4CACARAwAAmAIAIKgBAAC7AgAwqQEAAAcAEKoBAAC7AgAwqwEBAAAAAawBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb0BAQCbAgAh2gEBAJsCACHbAQEApwIAIdwBAQCnAgAh3QEBAKcCACHeAUAAvAIAId8BQAC8AgAh4AEBAKcCACHhAQEApwIAIQMAAAAHACABAAAIADACAAAJACAJAwAAmAIAIKgBAACVAgAwqQEAAAsAEKoBAACVAgAwqwEBAJsCACGsAQEAmwIAIbABQACXAgAhsQFAAJcCACHWAQAAlgIAIAEAAAALACAQBwAAmAIAIAwAALcCACANAAC0AgAgqAEAALgCADCpAQAADQAQqgEAALgCADCrAQEAmwIAIa0BAQCbAgAhsAFAAJcCACGxAUAAlwIAIcQBAQCbAgAhxQEBAJsCACHHAQAAuQLHASLIAQIAswIAIckBAQCnAgAhygEAALoCACAFBwAAoAMAIAwAAIIEACANAACBBAAgyQEAAL4CACDKAQAAvgIAIBAHAACYAgAgDAAAtwIAIA0AALQCACCoAQAAuAIAMKkBAAANABCqAQAAuAIAMKsBAQAAAAGtAQEAmwIAIbABQACXAgAhsQFAAJcCACHEAQEAmwIAIcUBAQCbAgAhxwEAALkCxwEiyAECALMCACHJAQEApwIAIcoBAAC6AgAgAwAAAA0AIAEAAA4AMAIAAA8AIBAKAACsAgAgDAAAtwIAIA4AAK0CACCoAQAAtQIAMKkBAAARABCqAQAAtQIAMKsBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb4BAQCbAgAhvwEBAKcCACHFAQEAmwIAIdEBAgCzAgAh0gEBAKcCACHTASAApgIAIdUBAAC2AtUBIgUKAAD9AwAgDAAAggQAIA4AAP4DACC_AQAAvgIAINIBAAC-AgAgEAoAAKwCACAMAAC3AgAgDgAArQIAIKgBAAC1AgAwqQEAABEAEKoBAAC1AgAwqwEBAAAAAbABQACXAgAhsQFAAJcCACG-AQEAmwIAIb8BAQCnAgAhxQEBAJsCACHRAQIAswIAIdIBAQCnAgAh0wEgAKYCACHVAQAAtgLVASIDAAAAEQAgAQAAEgAwAgAAEwAgAwAAAA0AIAEAAA4AMAIAAA8AIAEAAAARACABAAAADQAgAwAAAA0AIAEAAA4AMAIAAA8AIAwDAACYAgAgDQAAtAIAIKgBAACyAgAwqQEAABkAEKoBAACyAgAwqwEBAJsCACGsAQEAmwIAIa0BAQCbAgAhrgECALMCACGvAQEApwIAIbABQACXAgAhsQFAAJcCACEDAwAAoAMAIA0AAIEEACCvAQAAvgIAIA0DAACYAgAgDQAAtAIAIKgBAACyAgAwqQEAABkAEKoBAACyAgAwqwEBAAAAAawBAQCbAgAhrQEBAJsCACGuAQIAswIAIa8BAQCnAgAhsAFAAJcCACGxAUAAlwIAIfABAACxAgAgAwAAABkAIAEAABoAMAIAABsAIAEAAAANACABAAAAGQAgAwAAABkAIAEAABoAMAIAABsAIBAIAACYAgAgCQAAsAIAIAoAAKwCACCoAQAArwIAMKkBAAAgABCqAQAArwIAMKsBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb0BAQCbAgAhvgEBAJsCACG_AQEApwIAIcABAQCnAgAhwQEBAJsCACHCAQEAmwIAIcMBIACmAgAhBQgAAKADACAJAACABAAgCgAA_QMAIL8BAAC-AgAgwAEAAL4CACAQCAAAmAIAIAkAALACACAKAACsAgAgqAEAAK8CADCpAQAAIAAQqgEAAK8CADCrAQEAAAABsAFAAJcCACGxAUAAlwIAIb0BAQCbAgAhvgEBAJsCACG_AQEApwIAIcABAQCnAgAhwQEBAJsCACHCAQEAmwIAIcMBIACmAgAhAwAAACAAIAEAACEAMAIAACIAIAEAAAADACABAAAABwAgAQAAAA0AIAEAAAAZACABAAAAIAAgAQAAAAEAIBYEAACpAgAgBQAAqgIAIAYAAKsCACAKAACsAgAgDgAArQIAIA8AAK4CACCoAQAApQIAMKkBAAAqABCqAQAApQIAMKsBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb4BAQCbAgAhwAEBAKcCACHHAQEApwIAIeUBAQCbAgAh5gEgAKYCACHnAQEApwIAIekBAACoAukBIuoBAQCnAgAh6wEgAKYCACHsAQEApwIAIQsEAAD6AwAgBQAA-wMAIAYAAPwDACAKAAD9AwAgDgAA_gMAIA8AAP8DACDAAQAAvgIAIMcBAAC-AgAg5wEAAL4CACDqAQAAvgIAIOwBAAC-AgAgAwAAACoAIAEAACsAMAIAAAEAIAMAAAAqACABAAArADACAAABACADAAAAKgAgAQAAKwAwAgAAAQAgEwQAAPQDACAFAAD1AwAgBgAA9gMAIAoAAPcDACAOAAD4AwAgDwAA-QMAIKsBAQAAAAGwAUAAAAABsQFAAAAAAb4BAQAAAAHAAQEAAAABxwEBAAAAAeUBAQAAAAHmASAAAAAB5wEBAAAAAekBAAAA6QEC6gEBAAAAAesBIAAAAAHsAQEAAAABARUAAC8AIA2rAQEAAAABsAFAAAAAAbEBQAAAAAG-AQEAAAABwAEBAAAAAccBAQAAAAHlAQEAAAAB5gEgAAAAAecBAQAAAAHpAQAAAOkBAuoBAQAAAAHrASAAAAAB7AEBAAAAAQEVAAAxADABFQAAMQAwEwQAALMDACAFAAC0AwAgBgAAtQMAIAoAALYDACAOAAC3AwAgDwAAuAMAIKsBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb4BAQDEAgAhwAEBAMYCACHHAQEAxgIAIeUBAQDEAgAh5gEgAM8CACHnAQEAxgIAIekBAACyA-kBIuoBAQDGAgAh6wEgAM8CACHsAQEAxgIAIQIAAAABACAVAAA0ACANqwEBAMQCACGwAUAAxwIAIbEBQADHAgAhvgEBAMQCACHAAQEAxgIAIccBAQDGAgAh5QEBAMQCACHmASAAzwIAIecBAQDGAgAh6QEAALID6QEi6gEBAMYCACHrASAAzwIAIewBAQDGAgAhAgAAACoAIBUAADYAIAIAAAAqACAVAAA2ACADAAAAAQAgHAAALwAgHQAANAAgAQAAAAEAIAEAAAAqACAICwAArwMAICIAALEDACAjAACwAwAgwAEAAL4CACDHAQAAvgIAIOcBAAC-AgAg6gEAAL4CACDsAQAAvgIAIBCoAQAAoQIAMKkBAAA9ABCqAQAAoQIAMKsBAQD2AQAhsAFAAPkBACGxAUAA-QEAIb4BAQD2AQAhwAEBAPgBACHHAQEA-AEAIeUBAQD2AQAh5gEgAIUCACHnAQEA-AEAIekBAACiAukBIuoBAQD4AQAh6wEgAIUCACHsAQEA-AEAIQMAAAAqACABAAA8ADAhAAA9ACADAAAAKgAgAQAAKwAwAgAAAQAgAQAAAAUAIAEAAAAFACADAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACAJAwAArgMAIKsBAQAAAAGsAQEAAAABsAFAAAAAAbEBQAAAAAHZAUAAAAAB4gEBAAAAAeMBAQAAAAHkAQEAAAABARUAAEUAIAirAQEAAAABrAEBAAAAAbABQAAAAAGxAUAAAAAB2QFAAAAAAeIBAQAAAAHjAQEAAAAB5AEBAAAAAQEVAABHADABFQAARwAwCQMAAK0DACCrAQEAxAIAIawBAQDEAgAhsAFAAMcCACGxAUAAxwIAIdkBQADHAgAh4gEBAMQCACHjAQEAxgIAIeQBAQDGAgAhAgAAAAUAIBUAAEoAIAirAQEAxAIAIawBAQDEAgAhsAFAAMcCACGxAUAAxwIAIdkBQADHAgAh4gEBAMQCACHjAQEAxgIAIeQBAQDGAgAhAgAAAAMAIBUAAEwAIAIAAAADACAVAABMACADAAAABQAgHAAARQAgHQAASgAgAQAAAAUAIAEAAAADACAFCwAAqgMAICIAAKwDACAjAACrAwAg4wEAAL4CACDkAQAAvgIAIAuoAQAAoAIAMKkBAABTABCqAQAAoAIAMKsBAQD2AQAhrAEBAPYBACGwAUAA-QEAIbEBQAD5AQAh2QFAAPkBACHiAQEA9gEAIeMBAQD4AQAh5AEBAPgBACEDAAAAAwAgAQAAUgAwIQAAUwAgAwAAAAMAIAEAAAQAMAIAAAUAIAEAAAAJACABAAAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAMAAAAHACABAAAIADACAAAJACADAAAABwAgAQAACAAwAgAACQAgDgMAAKkDACCrAQEAAAABrAEBAAAAAbABQAAAAAGxAUAAAAABvQEBAAAAAdoBAQAAAAHbAQEAAAAB3AEBAAAAAd0BAQAAAAHeAUAAAAAB3wFAAAAAAeABAQAAAAHhAQEAAAABARUAAFsAIA2rAQEAAAABrAEBAAAAAbABQAAAAAGxAUAAAAABvQEBAAAAAdoBAQAAAAHbAQEAAAAB3AEBAAAAAd0BAQAAAAHeAUAAAAAB3wFAAAAAAeABAQAAAAHhAQEAAAABARUAAF0AMAEVAABdADAOAwAAqAMAIKsBAQDEAgAhrAEBAMQCACGwAUAAxwIAIbEBQADHAgAhvQEBAMQCACHaAQEAxAIAIdsBAQDGAgAh3AEBAMYCACHdAQEAxgIAId4BQACnAwAh3wFAAKcDACHgAQEAxgIAIeEBAQDGAgAhAgAAAAkAIBUAAGAAIA2rAQEAxAIAIawBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb0BAQDEAgAh2gEBAMQCACHbAQEAxgIAIdwBAQDGAgAh3QEBAMYCACHeAUAApwMAId8BQACnAwAh4AEBAMYCACHhAQEAxgIAIQIAAAAHACAVAABiACACAAAABwAgFQAAYgAgAwAAAAkAIBwAAFsAIB0AAGAAIAEAAAAJACABAAAABwAgCgsAAKQDACAiAACmAwAgIwAApQMAINsBAAC-AgAg3AEAAL4CACDdAQAAvgIAIN4BAAC-AgAg3wEAAL4CACDgAQAAvgIAIOEBAAC-AgAgEKgBAACcAgAwqQEAAGkAEKoBAACcAgAwqwEBAPYBACGsAQEA9gEAIbABQAD5AQAhsQFAAPkBACG9AQEA9gEAIdoBAQD2AQAh2wEBAPgBACHcAQEA-AEAId0BAQD4AQAh3gFAAJ0CACHfAUAAnQIAIeABAQD4AQAh4QEBAPgBACEDAAAABwAgAQAAaAAwIQAAaQAgAwAAAAcAIAEAAAgAMAIAAAkAIAmoAQAAmgIAMKkBAABvABCqAQAAmgIAMKsBAQAAAAGwAUAAlwIAIbEBQACXAgAh1wEBAJsCACHYAQEAmwIAIdkBQACXAgAhAQAAAGwAIAEAAABsACAJqAEAAJoCADCpAQAAbwAQqgEAAJoCADCrAQEAmwIAIbABQACXAgAhsQFAAJcCACHXAQEAmwIAIdgBAQCbAgAh2QFAAJcCACEAAwAAAG8AIAEAAHAAMAIAAGwAIAMAAABvACABAABwADACAABsACADAAAAbwAgAQAAcAAwAgAAbAAgBqsBAQAAAAGwAUAAAAABsQFAAAAAAdcBAQAAAAHYAQEAAAAB2QFAAAAAAQEVAAB0ACAGqwEBAAAAAbABQAAAAAGxAUAAAAAB1wEBAAAAAdgBAQAAAAHZAUAAAAABARUAAHYAMAEVAAB2ADAGqwEBAMQCACGwAUAAxwIAIbEBQADHAgAh1wEBAMQCACHYAQEAxAIAIdkBQADHAgAhAgAAAGwAIBUAAHkAIAarAQEAxAIAIbABQADHAgAhsQFAAMcCACHXAQEAxAIAIdgBAQDEAgAh2QFAAMcCACECAAAAbwAgFQAAewAgAgAAAG8AIBUAAHsAIAMAAABsACAcAAB0ACAdAAB5ACABAAAAbAAgAQAAAG8AIAMLAAChAwAgIgAAowMAICMAAKIDACAJqAEAAJkCADCpAQAAggEAEKoBAACZAgAwqwEBAPYBACGwAUAA-QEAIbEBQAD5AQAh1wEBAPYBACHYAQEA9gEAIdkBQAD5AQAhAwAAAG8AIAEAAIEBADAhAACCAQAgAwAAAG8AIAEAAHAAMAIAAGwAIAkDAACYAgAgqAEAAJUCADCpAQAACwAQqgEAAJUCADCrAQEAAAABrAEBAAAAAbABQACXAgAhsQFAAJcCACHWAQAAlgIAIAEAAACFAQAgAQAAAIUBACABAwAAoAMAIAMAAAALACABAACIAQAwAgAAhQEAIAMAAAALACABAACIAQAwAgAAhQEAIAMAAAALACABAACIAQAwAgAAhQEAIAYDAACfAwAgqwEBAAAAAawBAQAAAAGwAUAAAAABsQFAAAAAAdYBgAAAAAEBFQAAjAEAIAWrAQEAAAABrAEBAAAAAbABQAAAAAGxAUAAAAAB1gGAAAAAAQEVAACOAQAwARUAAI4BADAGAwAAngMAIKsBAQDEAgAhrAEBAMQCACGwAUAAxwIAIbEBQADHAgAh1gGAAAAAAQIAAACFAQAgFQAAkQEAIAWrAQEAxAIAIawBAQDEAgAhsAFAAMcCACGxAUAAxwIAIdYBgAAAAAECAAAACwAgFQAAkwEAIAIAAAALACAVAACTAQAgAwAAAIUBACAcAACMAQAgHQAAkQEAIAEAAACFAQAgAQAAAAsAIAMLAACbAwAgIgAAnQMAICMAAJwDACAIqAEAAJICADCpAQAAmgEAEKoBAACSAgAwqwEBAPYBACGsAQEA9gEAIbABQAD5AQAhsQFAAPkBACHWAQAAkwIAIAMAAAALACABAACZAQAwIQAAmgEAIAMAAAALACABAACIAQAwAgAAhQEAIAEAAAATACABAAAAEwAgAwAAABEAIAEAABIAMAIAABMAIAMAAAARACABAAASADACAAATACADAAAAEQAgAQAAEgAwAgAAEwAgDQoAAIoDACAMAACaAwAgDgAAiwMAIKsBAQAAAAGwAUAAAAABsQFAAAAAAb4BAQAAAAG_AQEAAAABxQEBAAAAAdEBAgAAAAHSAQEAAAAB0wEgAAAAAdUBAAAA1QECARUAAKIBACAKqwEBAAAAAbABQAAAAAGxAUAAAAABvgEBAAAAAb8BAQAAAAHFAQEAAAAB0QECAAAAAdIBAQAAAAHTASAAAAAB1QEAAADVAQIBFQAApAEAMAEVAACkAQAwDQoAAPACACAMAACZAwAgDgAA8QIAIKsBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb4BAQDEAgAhvwEBAMYCACHFAQEAxAIAIdEBAgDFAgAh0gEBAMYCACHTASAAzwIAIdUBAADuAtUBIgIAAAATACAVAACnAQAgCqsBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb4BAQDEAgAhvwEBAMYCACHFAQEAxAIAIdEBAgDFAgAh0gEBAMYCACHTASAAzwIAIdUBAADuAtUBIgIAAAARACAVAACpAQAgAgAAABEAIBUAAKkBACADAAAAEwAgHAAAogEAIB0AAKcBACABAAAAEwAgAQAAABEAIAcLAACUAwAgIgAAlwMAICMAAJYDACB0AACVAwAgdQAAmAMAIL8BAAC-AgAg0gEAAL4CACANqAEAAI4CADCpAQAAsAEAEKoBAACOAgAwqwEBAPYBACGwAUAA-QEAIbEBQAD5AQAhvgEBAPYBACG_AQEA-AEAIcUBAQD2AQAh0QECAPcBACHSAQEA-AEAIdMBIACFAgAh1QEAAI8C1QEiAwAAABEAIAEAAK8BADAhAACwAQAgAwAAABEAIAEAABIAMAIAABMAIAEAAAAPACABAAAADwAgAwAAAA0AIAEAAA4AMAIAAA8AIAMAAAANACABAAAOADACAAAPACADAAAADQAgAQAADgAwAgAADwAgDQcAAOICACAMAACIAwAgDQAA4wIAIKsBAQAAAAGtAQEAAAABsAFAAAAAAbEBQAAAAAHEAQEAAAABxQEBAAAAAccBAAAAxwECyAECAAAAAckBAQAAAAHKAYAAAAABARUAALgBACAKqwEBAAAAAa0BAQAAAAGwAUAAAAABsQFAAAAAAcQBAQAAAAHFAQEAAAABxwEAAADHAQLIAQIAAAAByQEBAAAAAcoBgAAAAAEBFQAAugEAMAEVAAC6AQAwDQcAAN8CACAMAACGAwAgDQAA4AIAIKsBAQDEAgAhrQEBAMQCACGwAUAAxwIAIbEBQADHAgAhxAEBAMQCACHFAQEAxAIAIccBAADdAscBIsgBAgDFAgAhyQEBAMYCACHKAYAAAAABAgAAAA8AIBUAAL0BACAKqwEBAMQCACGtAQEAxAIAIbABQADHAgAhsQFAAMcCACHEAQEAxAIAIcUBAQDEAgAhxwEAAN0CxwEiyAECAMUCACHJAQEAxgIAIcoBgAAAAAECAAAADQAgFQAAvwEAIAIAAAANACAVAAC_AQAgAwAAAA8AIBwAALgBACAdAAC9AQAgAQAAAA8AIAEAAAANACAHCwAAjwMAICIAAJIDACAjAACRAwAgdAAAkAMAIHUAAJMDACDJAQAAvgIAIMoBAAC-AgAgDagBAACIAgAwqQEAAMYBABCqAQAAiAIAMKsBAQD2AQAhrQEBAPYBACGwAUAA-QEAIbEBQAD5AQAhxAEBAPYBACHFAQEA9gEAIccBAACJAscBIsgBAgD3AQAhyQEBAPgBACHKAQAAigIAIAMAAAANACABAADFAQAwIQAAxgEAIAMAAAANACABAAAOADACAAAPACABAAAAIgAgAQAAACIAIAMAAAAgACABAAAhADACAAAiACADAAAAIAAgAQAAIQAwAgAAIgAgAwAAACAAIAEAACEAMAIAACIAIA0IAACMAwAgCQAAjQMAIAoAAI4DACCrAQEAAAABsAFAAAAAAbEBQAAAAAG9AQEAAAABvgEBAAAAAb8BAQAAAAHAAQEAAAABwQEBAAAAAcIBAQAAAAHDASAAAAABARUAAM4BACAKqwEBAAAAAbABQAAAAAGxAUAAAAABvQEBAAAAAb4BAQAAAAG_AQEAAAABwAEBAAAAAcEBAQAAAAHCAQEAAAABwwEgAAAAAQEVAADQAQAwARUAANABADANCAAA0AIAIAkAANECACAKAADSAgAgqwEBAMQCACGwAUAAxwIAIbEBQADHAgAhvQEBAMQCACG-AQEAxAIAIb8BAQDGAgAhwAEBAMYCACHBAQEAxAIAIcIBAQDEAgAhwwEgAM8CACECAAAAIgAgFQAA0wEAIAqrAQEAxAIAIbABQADHAgAhsQFAAMcCACG9AQEAxAIAIb4BAQDEAgAhvwEBAMYCACHAAQEAxgIAIcEBAQDEAgAhwgEBAMQCACHDASAAzwIAIQIAAAAgACAVAADVAQAgAgAAACAAIBUAANUBACADAAAAIgAgHAAAzgEAIB0AANMBACABAAAAIgAgAQAAACAAIAULAADMAgAgIgAAzgIAICMAAM0CACC_AQAAvgIAIMABAAC-AgAgDagBAACEAgAwqQEAANwBABCqAQAAhAIAMKsBAQD2AQAhsAFAAPkBACGxAUAA-QEAIb0BAQD2AQAhvgEBAPYBACG_AQEA-AEAIcABAQD4AQAhwQEBAPYBACHCAQEA9gEAIcMBIACFAgAhAwAAACAAIAEAANsBADAhAADcAQAgAwAAACAAIAEAACEAMAIAACIAIAEAAAAbACABAAAAGwAgAwAAABkAIAEAABoAMAIAABsAIAMAAAAZACABAAAaADACAAAbACADAAAAGQAgAQAAGgAwAgAAGwAgCQMAAMoCACANAADLAgAgqwEBAAAAAawBAQAAAAGtAQEAAAABrgECAAAAAa8BAQAAAAGwAUAAAAABsQFAAAAAAQEVAADkAQAgB6sBAQAAAAGsAQEAAAABrQEBAAAAAa4BAgAAAAGvAQEAAAABsAFAAAAAAbEBQAAAAAEBFQAA5gEAMAEVAADmAQAwCQMAAMgCACANAADJAgAgqwEBAMQCACGsAQEAxAIAIa0BAQDEAgAhrgECAMUCACGvAQEAxgIAIbABQADHAgAhsQFAAMcCACECAAAAGwAgFQAA6QEAIAerAQEAxAIAIawBAQDEAgAhrQEBAMQCACGuAQIAxQIAIa8BAQDGAgAhsAFAAMcCACGxAUAAxwIAIQIAAAAZACAVAADrAQAgAgAAABkAIBUAAOsBACADAAAAGwAgHAAA5AEAIB0AAOkBACABAAAAGwAgAQAAABkAIAYLAAC_AgAgIgAAwgIAICMAAMECACB0AADAAgAgdQAAwwIAIK8BAAC-AgAgCqgBAAD1AQAwqQEAAPIBABCqAQAA9QEAMKsBAQD2AQAhrAEBAPYBACGtAQEA9gEAIa4BAgD3AQAhrwEBAPgBACGwAUAA-QEAIbEBQAD5AQAhAwAAABkAIAEAAPEBADAhAADyAQAgAwAAABkAIAEAABoAMAIAABsAIAqoAQAA9QEAMKkBAADyAQAQqgEAAPUBADCrAQEA9gEAIawBAQD2AQAhrQEBAPYBACGuAQIA9wEAIa8BAQD4AQAhsAFAAPkBACGxAUAA-QEAIQ4LAAD7AQAgIgAAgwIAICMAAIMCACCyAQEAAAABswEBAAAABLQBAQAAAAS1AQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAAAABuQEBAIICACG6AQEAAAABuwEBAAAAAbwBAQAAAAENCwAA-wEAICIAAPsBACAjAAD7AQAgdAAAgQIAIHUAAPsBACCyAQIAAAABswECAAAABLQBAgAAAAS1AQIAAAABtgECAAAAAbcBAgAAAAG4AQIAAAABuQECAIACACEOCwAA_gEAICIAAP8BACAjAAD_AQAgsgEBAAAAAbMBAQAAAAW0AQEAAAAFtQEBAAAAAbYBAQAAAAG3AQEAAAABuAEBAAAAAbkBAQD9AQAhugEBAAAAAbsBAQAAAAG8AQEAAAABCwsAAPsBACAiAAD8AQAgIwAA_AEAILIBQAAAAAGzAUAAAAAEtAFAAAAABLUBQAAAAAG2AUAAAAABtwFAAAAAAbgBQAAAAAG5AUAA-gEAIQsLAAD7AQAgIgAA_AEAICMAAPwBACCyAUAAAAABswFAAAAABLQBQAAAAAS1AUAAAAABtgFAAAAAAbcBQAAAAAG4AUAAAAABuQFAAPoBACEIsgECAAAAAbMBAgAAAAS0AQIAAAAEtQECAAAAAbYBAgAAAAG3AQIAAAABuAECAAAAAbkBAgD7AQAhCLIBQAAAAAGzAUAAAAAEtAFAAAAABLUBQAAAAAG2AUAAAAABtwFAAAAAAbgBQAAAAAG5AUAA_AEAIQ4LAAD-AQAgIgAA_wEAICMAAP8BACCyAQEAAAABswEBAAAABbQBAQAAAAW1AQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAAAABuQEBAP0BACG6AQEAAAABuwEBAAAAAbwBAQAAAAEIsgECAAAAAbMBAgAAAAW0AQIAAAAFtQECAAAAAbYBAgAAAAG3AQIAAAABuAECAAAAAbkBAgD-AQAhC7IBAQAAAAGzAQEAAAAFtAEBAAAABbUBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQAAAAG5AQEA_wEAIboBAQAAAAG7AQEAAAABvAEBAAAAAQ0LAAD7AQAgIgAA-wEAICMAAPsBACB0AACBAgAgdQAA-wEAILIBAgAAAAGzAQIAAAAEtAECAAAABLUBAgAAAAG2AQIAAAABtwECAAAAAbgBAgAAAAG5AQIAgAIAIQiyAQgAAAABswEIAAAABLQBCAAAAAS1AQgAAAABtgEIAAAAAbcBCAAAAAG4AQgAAAABuQEIAIECACEOCwAA-wEAICIAAIMCACAjAACDAgAgsgEBAAAAAbMBAQAAAAS0AQEAAAAEtQEBAAAAAbYBAQAAAAG3AQEAAAABuAEBAAAAAbkBAQCCAgAhugEBAAAAAbsBAQAAAAG8AQEAAAABC7IBAQAAAAGzAQEAAAAEtAEBAAAABLUBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQAAAAG5AQEAgwIAIboBAQAAAAG7AQEAAAABvAEBAAAAAQ2oAQAAhAIAMKkBAADcAQAQqgEAAIQCADCrAQEA9gEAIbABQAD5AQAhsQFAAPkBACG9AQEA9gEAIb4BAQD2AQAhvwEBAPgBACHAAQEA-AEAIcEBAQD2AQAhwgEBAPYBACHDASAAhQIAIQULAAD7AQAgIgAAhwIAICMAAIcCACCyASAAAAABuQEgAIYCACEFCwAA-wEAICIAAIcCACAjAACHAgAgsgEgAAAAAbkBIACGAgAhArIBIAAAAAG5ASAAhwIAIQ2oAQAAiAIAMKkBAADGAQAQqgEAAIgCADCrAQEA9gEAIa0BAQD2AQAhsAFAAPkBACGxAUAA-QEAIcQBAQD2AQAhxQEBAPYBACHHAQAAiQLHASLIAQIA9wEAIckBAQD4AQAhygEAAIoCACAHCwAA-wEAICIAAI0CACAjAACNAgAgsgEAAADHAQKzAQAAAMcBCLQBAAAAxwEIuQEAAIwCxwEiDwsAAP4BACAiAACLAgAgIwAAiwIAILIBgAAAAAG1AYAAAAABtgGAAAAAAbcBgAAAAAG4AYAAAAABuQGAAAAAAcsBAQAAAAHMAQEAAAABzQEBAAAAAc4BgAAAAAHPAYAAAAAB0AGAAAAAAQyyAYAAAAABtQGAAAAAAbYBgAAAAAG3AYAAAAABuAGAAAAAAbkBgAAAAAHLAQEAAAABzAEBAAAAAc0BAQAAAAHOAYAAAAABzwGAAAAAAdABgAAAAAEHCwAA-wEAICIAAI0CACAjAACNAgAgsgEAAADHAQKzAQAAAMcBCLQBAAAAxwEIuQEAAIwCxwEiBLIBAAAAxwECswEAAADHAQi0AQAAAMcBCLkBAACNAscBIg2oAQAAjgIAMKkBAACwAQAQqgEAAI4CADCrAQEA9gEAIbABQAD5AQAhsQFAAPkBACG-AQEA9gEAIb8BAQD4AQAhxQEBAPYBACHRAQIA9wEAIdIBAQD4AQAh0wEgAIUCACHVAQAAjwLVASIHCwAA-wEAICIAAJECACAjAACRAgAgsgEAAADVAQKzAQAAANUBCLQBAAAA1QEIuQEAAJAC1QEiBwsAAPsBACAiAACRAgAgIwAAkQIAILIBAAAA1QECswEAAADVAQi0AQAAANUBCLkBAACQAtUBIgSyAQAAANUBArMBAAAA1QEItAEAAADVAQi5AQAAkQLVASIIqAEAAJICADCpAQAAmgEAEKoBAACSAgAwqwEBAPYBACGsAQEA9gEAIbABQAD5AQAhsQFAAPkBACHWAQAAkwIAIA8LAAD7AQAgIgAAlAIAICMAAJQCACCyAYAAAAABtQGAAAAAAbYBgAAAAAG3AYAAAAABuAGAAAAAAbkBgAAAAAHLAQEAAAABzAEBAAAAAc0BAQAAAAHOAYAAAAABzwGAAAAAAdABgAAAAAEMsgGAAAAAAbUBgAAAAAG2AYAAAAABtwGAAAAAAbgBgAAAAAG5AYAAAAABywEBAAAAAcwBAQAAAAHNAQEAAAABzgGAAAAAAc8BgAAAAAHQAYAAAAABCQMAAJgCACCoAQAAlQIAMKkBAAALABCqAQAAlQIAMKsBAQCbAgAhrAEBAJsCACGwAUAAlwIAIbEBQACXAgAh1gEAAJYCACAMsgGAAAAAAbUBgAAAAAG2AYAAAAABtwGAAAAAAbgBgAAAAAG5AYAAAAABywEBAAAAAcwBAQAAAAHNAQEAAAABzgGAAAAAAc8BgAAAAAHQAYAAAAABCLIBQAAAAAGzAUAAAAAEtAFAAAAABLUBQAAAAAG2AUAAAAABtwFAAAAAAbgBQAAAAAG5AUAA_AEAIRgEAACpAgAgBQAAqgIAIAYAAKsCACAKAACsAgAgDgAArQIAIA8AAK4CACCoAQAApQIAMKkBAAAqABCqAQAApQIAMKsBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb4BAQCbAgAhwAEBAKcCACHHAQEApwIAIeUBAQCbAgAh5gEgAKYCACHnAQEApwIAIekBAACoAukBIuoBAQCnAgAh6wEgAKYCACHsAQEApwIAIfEBAAAqACDyAQAAKgAgCagBAACZAgAwqQEAAIIBABCqAQAAmQIAMKsBAQD2AQAhsAFAAPkBACGxAUAA-QEAIdcBAQD2AQAh2AEBAPYBACHZAUAA-QEAIQmoAQAAmgIAMKkBAABvABCqAQAAmgIAMKsBAQCbAgAhsAFAAJcCACGxAUAAlwIAIdcBAQCbAgAh2AEBAJsCACHZAUAAlwIAIQuyAQEAAAABswEBAAAABLQBAQAAAAS1AQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAAAABuQEBAIMCACG6AQEAAAABuwEBAAAAAbwBAQAAAAEQqAEAAJwCADCpAQAAaQAQqgEAAJwCADCrAQEA9gEAIawBAQD2AQAhsAFAAPkBACGxAUAA-QEAIb0BAQD2AQAh2gEBAPYBACHbAQEA-AEAIdwBAQD4AQAh3QEBAPgBACHeAUAAnQIAId8BQACdAgAh4AEBAPgBACHhAQEA-AEAIQsLAAD-AQAgIgAAnwIAICMAAJ8CACCyAUAAAAABswFAAAAABbQBQAAAAAW1AUAAAAABtgFAAAAAAbcBQAAAAAG4AUAAAAABuQFAAJ4CACELCwAA_gEAICIAAJ8CACAjAACfAgAgsgFAAAAAAbMBQAAAAAW0AUAAAAAFtQFAAAAAAbYBQAAAAAG3AUAAAAABuAFAAAAAAbkBQACeAgAhCLIBQAAAAAGzAUAAAAAFtAFAAAAABbUBQAAAAAG2AUAAAAABtwFAAAAAAbgBQAAAAAG5AUAAnwIAIQuoAQAAoAIAMKkBAABTABCqAQAAoAIAMKsBAQD2AQAhrAEBAPYBACGwAUAA-QEAIbEBQAD5AQAh2QFAAPkBACHiAQEA9gEAIeMBAQD4AQAh5AEBAPgBACEQqAEAAKECADCpAQAAPQAQqgEAAKECADCrAQEA9gEAIbABQAD5AQAhsQFAAPkBACG-AQEA9gEAIcABAQD4AQAhxwEBAPgBACHlAQEA9gEAIeYBIACFAgAh5wEBAPgBACHpAQAAogLpASLqAQEA-AEAIesBIACFAgAh7AEBAPgBACEHCwAA-wEAICIAAKQCACAjAACkAgAgsgEAAADpAQKzAQAAAOkBCLQBAAAA6QEIuQEAAKMC6QEiBwsAAPsBACAiAACkAgAgIwAApAIAILIBAAAA6QECswEAAADpAQi0AQAAAOkBCLkBAACjAukBIgSyAQAAAOkBArMBAAAA6QEItAEAAADpAQi5AQAApALpASIWBAAAqQIAIAUAAKoCACAGAACrAgAgCgAArAIAIA4AAK0CACAPAACuAgAgqAEAAKUCADCpAQAAKgAQqgEAAKUCADCrAQEAmwIAIbABQACXAgAhsQFAAJcCACG-AQEAmwIAIcABAQCnAgAhxwEBAKcCACHlAQEAmwIAIeYBIACmAgAh5wEBAKcCACHpAQAAqALpASLqAQEApwIAIesBIACmAgAh7AEBAKcCACECsgEgAAAAAbkBIACHAgAhC7IBAQAAAAGzAQEAAAAFtAEBAAAABbUBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQAAAAG5AQEA_wEAIboBAQAAAAG7AQEAAAABvAEBAAAAAQSyAQAAAOkBArMBAAAA6QEItAEAAADpAQi5AQAApALpASID7QEAAAMAIO4BAAADACDvAQAAAwAgA-0BAAAHACDuAQAABwAg7wEAAAcAIAsDAACYAgAgqAEAAJUCADCpAQAACwAQqgEAAJUCADCrAQEAmwIAIawBAQCbAgAhsAFAAJcCACGxAUAAlwIAIdYBAACWAgAg8QEAAAsAIPIBAAALACAD7QEAAA0AIO4BAAANACDvAQAADQAgA-0BAAAZACDuAQAAGQAg7wEAABkAIAPtAQAAIAAg7gEAACAAIO8BAAAgACAQCAAAmAIAIAkAALACACAKAACsAgAgqAEAAK8CADCpAQAAIAAQqgEAAK8CADCrAQEAmwIAIbABQACXAgAhsQFAAJcCACG9AQEAmwIAIb4BAQCbAgAhvwEBAKcCACHAAQEApwIAIcEBAQCbAgAhwgEBAJsCACHDASAApgIAIQPtAQAAEQAg7gEAABEAIO8BAAARACACrAEBAAAAAa0BAQAAAAEMAwAAmAIAIA0AALQCACCoAQAAsgIAMKkBAAAZABCqAQAAsgIAMKsBAQCbAgAhrAEBAJsCACGtAQEAmwIAIa4BAgCzAgAhrwEBAKcCACGwAUAAlwIAIbEBQACXAgAhCLIBAgAAAAGzAQIAAAAEtAECAAAABLUBAgAAAAG2AQIAAAABtwECAAAAAbgBAgAAAAG5AQIA-wEAIRIKAACsAgAgDAAAtwIAIA4AAK0CACCoAQAAtQIAMKkBAAARABCqAQAAtQIAMKsBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb4BAQCbAgAhvwEBAKcCACHFAQEAmwIAIdEBAgCzAgAh0gEBAKcCACHTASAApgIAIdUBAAC2AtUBIvEBAAARACDyAQAAEQAgEAoAAKwCACAMAAC3AgAgDgAArQIAIKgBAAC1AgAwqQEAABEAEKoBAAC1AgAwqwEBAJsCACGwAUAAlwIAIbEBQACXAgAhvgEBAJsCACG_AQEApwIAIcUBAQCbAgAh0QECALMCACHSAQEApwIAIdMBIACmAgAh1QEAALYC1QEiBLIBAAAA1QECswEAAADVAQi0AQAAANUBCLkBAACRAtUBIhIIAACYAgAgCQAAsAIAIAoAAKwCACCoAQAArwIAMKkBAAAgABCqAQAArwIAMKsBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb0BAQCbAgAhvgEBAJsCACG_AQEApwIAIcABAQCnAgAhwQEBAJsCACHCAQEAmwIAIcMBIACmAgAh8QEAACAAIPIBAAAgACAQBwAAmAIAIAwAALcCACANAAC0AgAgqAEAALgCADCpAQAADQAQqgEAALgCADCrAQEAmwIAIa0BAQCbAgAhsAFAAJcCACGxAUAAlwIAIcQBAQCbAgAhxQEBAJsCACHHAQAAuQLHASLIAQIAswIAIckBAQCnAgAhygEAALoCACAEsgEAAADHAQKzAQAAAMcBCLQBAAAAxwEIuQEAAI0CxwEiDLIBgAAAAAG1AYAAAAABtgGAAAAAAbcBgAAAAAG4AYAAAAABuQGAAAAAAcsBAQAAAAHMAQEAAAABzQEBAAAAAc4BgAAAAAHPAYAAAAAB0AGAAAAAAREDAACYAgAgqAEAALsCADCpAQAABwAQqgEAALsCADCrAQEAmwIAIawBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb0BAQCbAgAh2gEBAJsCACHbAQEApwIAIdwBAQCnAgAh3QEBAKcCACHeAUAAvAIAId8BQAC8AgAh4AEBAKcCACHhAQEApwIAIQiyAUAAAAABswFAAAAABbQBQAAAAAW1AUAAAAABtgFAAAAAAbcBQAAAAAG4AUAAAAABuQFAAJ8CACEMAwAAmAIAIKgBAAC9AgAwqQEAAAMAEKoBAAC9AgAwqwEBAJsCACGsAQEAmwIAIbABQACXAgAhsQFAAJcCACHZAUAAlwIAIeIBAQCbAgAh4wEBAKcCACHkAQEApwIAIQAAAAAAAAH2AQEAAAABBfYBAgAAAAH8AQIAAAAB_QECAAAAAf4BAgAAAAH_AQIAAAABAfYBAQAAAAEB9gFAAAAAAQUcAAC2BAAgHQAAvAQAIPMBAAC3BAAg9AEAALsEACD5AQAAAQAgBRwAALQEACAdAAC5BAAg8wEAALUEACD0AQAAuAQAIPkBAAATACADHAAAtgQAIPMBAAC3BAAg-QEAAAEAIAMcAAC0BAAg8wEAALUEACD5AQAAEwAgAAAAAfYBIAAAAAEFHAAAnAQAIB0AALIEACDzAQAAnQQAIPQBAACxBAAg-QEAAAEAIAscAADkAgAwHQAA6QIAMPMBAADlAgAw9AEAAOYCADD1AQAA5wIAIPYBAADoAgAw9wEAAOgCADD4AQAA6AIAMPkBAADoAgAw-gEAAOoCADD7AQAA6wIAMAscAADTAgAwHQAA2AIAMPMBAADUAgAw9AEAANUCADD1AQAA1gIAIPYBAADXAgAw9wEAANcCADD4AQAA1wIAMPkBAADXAgAw-gEAANkCADD7AQAA2gIAMAsHAADiAgAgDQAA4wIAIKsBAQAAAAGtAQEAAAABsAFAAAAAAbEBQAAAAAHEAQEAAAABxwEAAADHAQLIAQIAAAAByQEBAAAAAcoBgAAAAAECAAAADwAgHAAA4QIAIAMAAAAPACAcAADhAgAgHQAA3gIAIAEVAACwBAAwEAcAAJgCACAMAAC3AgAgDQAAtAIAIKgBAAC4AgAwqQEAAA0AEKoBAAC4AgAwqwEBAAAAAa0BAQCbAgAhsAFAAJcCACGxAUAAlwIAIcQBAQCbAgAhxQEBAJsCACHHAQAAuQLHASLIAQIAswIAIckBAQCnAgAhygEAALoCACACAAAADwAgFQAA3gIAIAIAAADbAgAgFQAA3AIAIA2oAQAA2gIAMKkBAADbAgAQqgEAANoCADCrAQEAmwIAIa0BAQCbAgAhsAFAAJcCACGxAUAAlwIAIcQBAQCbAgAhxQEBAJsCACHHAQAAuQLHASLIAQIAswIAIckBAQCnAgAhygEAALoCACANqAEAANoCADCpAQAA2wIAEKoBAADaAgAwqwEBAJsCACGtAQEAmwIAIbABQACXAgAhsQFAAJcCACHEAQEAmwIAIcUBAQCbAgAhxwEAALkCxwEiyAECALMCACHJAQEApwIAIcoBAAC6AgAgCasBAQDEAgAhrQEBAMQCACGwAUAAxwIAIbEBQADHAgAhxAEBAMQCACHHAQAA3QLHASLIAQIAxQIAIckBAQDGAgAhygGAAAAAAQH2AQAAAMcBAgsHAADfAgAgDQAA4AIAIKsBAQDEAgAhrQEBAMQCACGwAUAAxwIAIbEBQADHAgAhxAEBAMQCACHHAQAA3QLHASLIAQIAxQIAIckBAQDGAgAhygGAAAAAAQUcAACoBAAgHQAArgQAIPMBAACpBAAg9AEAAK0EACD5AQAAAQAgBRwAAKYEACAdAACrBAAg8wEAAKcEACD0AQAAqgQAIPkBAAATACALBwAA4gIAIA0AAOMCACCrAQEAAAABrQEBAAAAAbABQAAAAAGxAUAAAAABxAEBAAAAAccBAAAAxwECyAECAAAAAckBAQAAAAHKAYAAAAABAxwAAKgEACDzAQAAqQQAIPkBAAABACADHAAApgQAIPMBAACnBAAg-QEAABMAIAsKAACKAwAgDgAAiwMAIKsBAQAAAAGwAUAAAAABsQFAAAAAAb4BAQAAAAG_AQEAAAAB0QECAAAAAdIBAQAAAAHTASAAAAAB1QEAAADVAQICAAAAEwAgHAAAiQMAIAMAAAATACAcAACJAwAgHQAA7wIAIAEVAAClBAAwEAoAAKwCACAMAAC3AgAgDgAArQIAIKgBAAC1AgAwqQEAABEAEKoBAAC1AgAwqwEBAAAAAbABQACXAgAhsQFAAJcCACG-AQEAmwIAIb8BAQCnAgAhxQEBAJsCACHRAQIAswIAIdIBAQCnAgAh0wEgAKYCACHVAQAAtgLVASICAAAAEwAgFQAA7wIAIAIAAADsAgAgFQAA7QIAIA2oAQAA6wIAMKkBAADsAgAQqgEAAOsCADCrAQEAmwIAIbABQACXAgAhsQFAAJcCACG-AQEAmwIAIb8BAQCnAgAhxQEBAJsCACHRAQIAswIAIdIBAQCnAgAh0wEgAKYCACHVAQAAtgLVASINqAEAAOsCADCpAQAA7AIAEKoBAADrAgAwqwEBAJsCACGwAUAAlwIAIbEBQACXAgAhvgEBAJsCACG_AQEApwIAIcUBAQCbAgAh0QECALMCACHSAQEApwIAIdMBIACmAgAh1QEAALYC1QEiCasBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb4BAQDEAgAhvwEBAMYCACHRAQIAxQIAIdIBAQDGAgAh0wEgAM8CACHVAQAA7gLVASIB9gEAAADVAQILCgAA8AIAIA4AAPECACCrAQEAxAIAIbABQADHAgAhsQFAAMcCACG-AQEAxAIAIb8BAQDGAgAh0QECAMUCACHSAQEAxgIAIdMBIADPAgAh1QEAAO4C1QEiCxwAAP4CADAdAACCAwAw8wEAAP8CADD0AQAAgAMAMPUBAACBAwAg9gEAANcCADD3AQAA1wIAMPgBAADXAgAw-QEAANcCADD6AQAAgwMAMPsBAADaAgAwCxwAAPICADAdAAD3AgAw8wEAAPMCADD0AQAA9AIAMPUBAAD1AgAg9gEAAPYCADD3AQAA9gIAMPgBAAD2AgAw-QEAAPYCADD6AQAA-AIAMPsBAAD5AgAwBwMAAMoCACCrAQEAAAABrAEBAAAAAa4BAgAAAAGvAQEAAAABsAFAAAAAAbEBQAAAAAECAAAAGwAgHAAA_QIAIAMAAAAbACAcAAD9AgAgHQAA_AIAIAEVAACkBAAwDQMAAJgCACANAAC0AgAgqAEAALICADCpAQAAGQAQqgEAALICADCrAQEAAAABrAEBAJsCACGtAQEAmwIAIa4BAgCzAgAhrwEBAKcCACGwAUAAlwIAIbEBQACXAgAh8AEAALECACACAAAAGwAgFQAA_AIAIAIAAAD6AgAgFQAA-wIAIAqoAQAA-QIAMKkBAAD6AgAQqgEAAPkCADCrAQEAmwIAIawBAQCbAgAhrQEBAJsCACGuAQIAswIAIa8BAQCnAgAhsAFAAJcCACGxAUAAlwIAIQqoAQAA-QIAMKkBAAD6AgAQqgEAAPkCADCrAQEAmwIAIawBAQCbAgAhrQEBAJsCACGuAQIAswIAIa8BAQCnAgAhsAFAAJcCACGxAUAAlwIAIQarAQEAxAIAIawBAQDEAgAhrgECAMUCACGvAQEAxgIAIbABQADHAgAhsQFAAMcCACEHAwAAyAIAIKsBAQDEAgAhrAEBAMQCACGuAQIAxQIAIa8BAQDGAgAhsAFAAMcCACGxAUAAxwIAIQcDAADKAgAgqwEBAAAAAawBAQAAAAGuAQIAAAABrwEBAAAAAbABQAAAAAGxAUAAAAABCwcAAOICACAMAACIAwAgqwEBAAAAAbABQAAAAAGxAUAAAAABxAEBAAAAAcUBAQAAAAHHAQAAAMcBAsgBAgAAAAHJAQEAAAABygGAAAAAAQIAAAAPACAcAACHAwAgAwAAAA8AIBwAAIcDACAdAACFAwAgARUAAKMEADACAAAADwAgFQAAhQMAIAIAAADbAgAgFQAAhAMAIAmrAQEAxAIAIbABQADHAgAhsQFAAMcCACHEAQEAxAIAIcUBAQDEAgAhxwEAAN0CxwEiyAECAMUCACHJAQEAxgIAIcoBgAAAAAELBwAA3wIAIAwAAIYDACCrAQEAxAIAIbABQADHAgAhsQFAAMcCACHEAQEAxAIAIcUBAQDEAgAhxwEAAN0CxwEiyAECAMUCACHJAQEAxgIAIcoBgAAAAAEFHAAAngQAIB0AAKEEACDzAQAAnwQAIPQBAACgBAAg-QEAACIAIAsHAADiAgAgDAAAiAMAIKsBAQAAAAGwAUAAAAABsQFAAAAAAcQBAQAAAAHFAQEAAAABxwEAAADHAQLIAQIAAAAByQEBAAAAAcoBgAAAAAEDHAAAngQAIPMBAACfBAAg-QEAACIAIAsKAACKAwAgDgAAiwMAIKsBAQAAAAGwAUAAAAABsQFAAAAAAb4BAQAAAAG_AQEAAAAB0QECAAAAAdIBAQAAAAHTASAAAAAB1QEAAADVAQIEHAAA_gIAMPMBAAD_AgAw9QEAAIEDACD5AQAA1wIAMAQcAADyAgAw8wEAAPMCADD1AQAA9QIAIPkBAAD2AgAwAxwAAJwEACDzAQAAnQQAIPkBAAABACAEHAAA5AIAMPMBAADlAgAw9QEAAOcCACD5AQAA6AIAMAQcAADTAgAw8wEAANQCADD1AQAA1gIAIPkBAADXAgAwAAAAAAAAAAAAAAUcAACXBAAgHQAAmgQAIPMBAACYBAAg9AEAAJkEACD5AQAAIgAgAxwAAJcEACDzAQAAmAQAIPkBAAAiACAAAAAFHAAAkgQAIB0AAJUEACDzAQAAkwQAIPQBAACUBAAg-QEAAAEAIAMcAACSBAAg8wEAAJMEACD5AQAAAQAgCwQAAPoDACAFAAD7AwAgBgAA_AMAIAoAAP0DACAOAAD-AwAgDwAA_wMAIMABAAC-AgAgxwEAAL4CACDnAQAAvgIAIOoBAAC-AgAg7AEAAL4CACAAAAAAAAAB9gFAAAAAAQUcAACNBAAgHQAAkAQAIPMBAACOBAAg9AEAAI8EACD5AQAAAQAgAxwAAI0EACDzAQAAjgQAIPkBAAABACAAAAAFHAAAiAQAIB0AAIsEACDzAQAAiQQAIPQBAACKBAAg-QEAAAEAIAMcAACIBAAg8wEAAIkEACD5AQAAAQAgAAAAAfYBAAAA6QECCxwAAOgDADAdAADtAwAw8wEAAOkDADD0AQAA6gMAMPUBAADrAwAg9gEAAOwDADD3AQAA7AMAMPgBAADsAwAw-QEAAOwDADD6AQAA7gMAMPsBAADvAwAwCxwAANwDADAdAADhAwAw8wEAAN0DADD0AQAA3gMAMPUBAADfAwAg9gEAAOADADD3AQAA4AMAMPgBAADgAwAw-QEAAOADADD6AQAA4gMAMPsBAADjAwAwBxwAANcDACAdAADaAwAg8wEAANgDACD0AQAA2QMAIPcBAAALACD4AQAACwAg-QEAAIUBACALHAAAzgMAMB0AANIDADDzAQAAzwMAMPQBAADQAwAw9QEAANEDACD2AQAA1wIAMPcBAADXAgAw-AEAANcCADD5AQAA1wIAMPoBAADTAwAw-wEAANoCADALHAAAxQMAMB0AAMkDADDzAQAAxgMAMPQBAADHAwAw9QEAAMgDACD2AQAA9gIAMPcBAAD2AgAw-AEAAPYCADD5AQAA9gIAMPoBAADKAwAw-wEAAPkCADALHAAAuQMAMB0AAL4DADDzAQAAugMAMPQBAAC7AwAw9QEAALwDACD2AQAAvQMAMPcBAAC9AwAw-AEAAL0DADD5AQAAvQMAMPoBAAC_AwAw-wEAAMADADALCQAAjQMAIAoAAI4DACCrAQEAAAABsAFAAAAAAbEBQAAAAAG-AQEAAAABvwEBAAAAAcABAQAAAAHBAQEAAAABwgEBAAAAAcMBIAAAAAECAAAAIgAgHAAAxAMAIAMAAAAiACAcAADEAwAgHQAAwwMAIAEVAACHBAAwEAgAAJgCACAJAACwAgAgCgAArAIAIKgBAACvAgAwqQEAACAAEKoBAACvAgAwqwEBAAAAAbABQACXAgAhsQFAAJcCACG9AQEAmwIAIb4BAQCbAgAhvwEBAKcCACHAAQEApwIAIcEBAQCbAgAhwgEBAJsCACHDASAApgIAIQIAAAAiACAVAADDAwAgAgAAAMEDACAVAADCAwAgDagBAADAAwAwqQEAAMEDABCqAQAAwAMAMKsBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb0BAQCbAgAhvgEBAJsCACG_AQEApwIAIcABAQCnAgAhwQEBAJsCACHCAQEAmwIAIcMBIACmAgAhDagBAADAAwAwqQEAAMEDABCqAQAAwAMAMKsBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb0BAQCbAgAhvgEBAJsCACG_AQEApwIAIcABAQCnAgAhwQEBAJsCACHCAQEAmwIAIcMBIACmAgAhCasBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb4BAQDEAgAhvwEBAMYCACHAAQEAxgIAIcEBAQDEAgAhwgEBAMQCACHDASAAzwIAIQsJAADRAgAgCgAA0gIAIKsBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb4BAQDEAgAhvwEBAMYCACHAAQEAxgIAIcEBAQDEAgAhwgEBAMQCACHDASAAzwIAIQsJAACNAwAgCgAAjgMAIKsBAQAAAAGwAUAAAAABsQFAAAAAAb4BAQAAAAG_AQEAAAABwAEBAAAAAcEBAQAAAAHCAQEAAAABwwEgAAAAAQcNAADLAgAgqwEBAAAAAa0BAQAAAAGuAQIAAAABrwEBAAAAAbABQAAAAAGxAUAAAAABAgAAABsAIBwAAM0DACADAAAAGwAgHAAAzQMAIB0AAMwDACABFQAAhgQAMAIAAAAbACAVAADMAwAgAgAAAPoCACAVAADLAwAgBqsBAQDEAgAhrQEBAMQCACGuAQIAxQIAIa8BAQDGAgAhsAFAAMcCACGxAUAAxwIAIQcNAADJAgAgqwEBAMQCACGtAQEAxAIAIa4BAgDFAgAhrwEBAMYCACGwAUAAxwIAIbEBQADHAgAhBw0AAMsCACCrAQEAAAABrQEBAAAAAa4BAgAAAAGvAQEAAAABsAFAAAAAAbEBQAAAAAELDAAAiAMAIA0AAOMCACCrAQEAAAABrQEBAAAAAbABQAAAAAGxAUAAAAABxQEBAAAAAccBAAAAxwECyAECAAAAAckBAQAAAAHKAYAAAAABAgAAAA8AIBwAANYDACADAAAADwAgHAAA1gMAIB0AANUDACABFQAAhQQAMAIAAAAPACAVAADVAwAgAgAAANsCACAVAADUAwAgCasBAQDEAgAhrQEBAMQCACGwAUAAxwIAIbEBQADHAgAhxQEBAMQCACHHAQAA3QLHASLIAQIAxQIAIckBAQDGAgAhygGAAAAAAQsMAACGAwAgDQAA4AIAIKsBAQDEAgAhrQEBAMQCACGwAUAAxwIAIbEBQADHAgAhxQEBAMQCACHHAQAA3QLHASLIAQIAxQIAIckBAQDGAgAhygGAAAAAAQsMAACIAwAgDQAA4wIAIKsBAQAAAAGtAQEAAAABsAFAAAAAAbEBQAAAAAHFAQEAAAABxwEAAADHAQLIAQIAAAAByQEBAAAAAcoBgAAAAAEEqwEBAAAAAbABQAAAAAGxAUAAAAAB1gGAAAAAAQIAAACFAQAgHAAA1wMAIAMAAAALACAcAADXAwAgHQAA2wMAIAYAAAALACAVAADbAwAgqwEBAMQCACGwAUAAxwIAIbEBQADHAgAh1gGAAAAAAQSrAQEAxAIAIbABQADHAgAhsQFAAMcCACHWAYAAAAABDKsBAQAAAAGwAUAAAAABsQFAAAAAAb0BAQAAAAHaAQEAAAAB2wEBAAAAAdwBAQAAAAHdAQEAAAAB3gFAAAAAAd8BQAAAAAHgAQEAAAAB4QEBAAAAAQIAAAAJACAcAADnAwAgAwAAAAkAIBwAAOcDACAdAADmAwAgARUAAIQEADARAwAAmAIAIKgBAAC7AgAwqQEAAAcAEKoBAAC7AgAwqwEBAAAAAawBAQCbAgAhsAFAAJcCACGxAUAAlwIAIb0BAQCbAgAh2gEBAJsCACHbAQEApwIAIdwBAQCnAgAh3QEBAKcCACHeAUAAvAIAId8BQAC8AgAh4AEBAKcCACHhAQEApwIAIQIAAAAJACAVAADmAwAgAgAAAOQDACAVAADlAwAgEKgBAADjAwAwqQEAAOQDABCqAQAA4wMAMKsBAQCbAgAhrAEBAJsCACGwAUAAlwIAIbEBQACXAgAhvQEBAJsCACHaAQEAmwIAIdsBAQCnAgAh3AEBAKcCACHdAQEApwIAId4BQAC8AgAh3wFAALwCACHgAQEApwIAIeEBAQCnAgAhEKgBAADjAwAwqQEAAOQDABCqAQAA4wMAMKsBAQCbAgAhrAEBAJsCACGwAUAAlwIAIbEBQACXAgAhvQEBAJsCACHaAQEAmwIAIdsBAQCnAgAh3AEBAKcCACHdAQEApwIAId4BQAC8AgAh3wFAALwCACHgAQEApwIAIeEBAQCnAgAhDKsBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb0BAQDEAgAh2gEBAMQCACHbAQEAxgIAIdwBAQDGAgAh3QEBAMYCACHeAUAApwMAId8BQACnAwAh4AEBAMYCACHhAQEAxgIAIQyrAQEAxAIAIbABQADHAgAhsQFAAMcCACG9AQEAxAIAIdoBAQDEAgAh2wEBAMYCACHcAQEAxgIAId0BAQDGAgAh3gFAAKcDACHfAUAApwMAIeABAQDGAgAh4QEBAMYCACEMqwEBAAAAAbABQAAAAAGxAUAAAAABvQEBAAAAAdoBAQAAAAHbAQEAAAAB3AEBAAAAAd0BAQAAAAHeAUAAAAAB3wFAAAAAAeABAQAAAAHhAQEAAAABB6sBAQAAAAGwAUAAAAABsQFAAAAAAdkBQAAAAAHiAQEAAAAB4wEBAAAAAeQBAQAAAAECAAAABQAgHAAA8wMAIAMAAAAFACAcAADzAwAgHQAA8gMAIAEVAACDBAAwDAMAAJgCACCoAQAAvQIAMKkBAAADABCqAQAAvQIAMKsBAQAAAAGsAQEAmwIAIbABQACXAgAhsQFAAJcCACHZAUAAlwIAIeIBAQAAAAHjAQEApwIAIeQBAQCnAgAhAgAAAAUAIBUAAPIDACACAAAA8AMAIBUAAPEDACALqAEAAO8DADCpAQAA8AMAEKoBAADvAwAwqwEBAJsCACGsAQEAmwIAIbABQACXAgAhsQFAAJcCACHZAUAAlwIAIeIBAQCbAgAh4wEBAKcCACHkAQEApwIAIQuoAQAA7wMAMKkBAADwAwAQqgEAAO8DADCrAQEAmwIAIawBAQCbAgAhsAFAAJcCACGxAUAAlwIAIdkBQACXAgAh4gEBAJsCACHjAQEApwIAIeQBAQCnAgAhB6sBAQDEAgAhsAFAAMcCACGxAUAAxwIAIdkBQADHAgAh4gEBAMQCACHjAQEAxgIAIeQBAQDGAgAhB6sBAQDEAgAhsAFAAMcCACGxAUAAxwIAIdkBQADHAgAh4gEBAMQCACHjAQEAxgIAIeQBAQDGAgAhB6sBAQAAAAGwAUAAAAABsQFAAAAAAdkBQAAAAAHiAQEAAAAB4wEBAAAAAeQBAQAAAAEEHAAA6AMAMPMBAADpAwAw9QEAAOsDACD5AQAA7AMAMAQcAADcAwAw8wEAAN0DADD1AQAA3wMAIPkBAADgAwAwAxwAANcDACDzAQAA2AMAIPkBAACFAQAgBBwAAM4DADDzAQAAzwMAMPUBAADRAwAg-QEAANcCADAEHAAAxQMAMPMBAADGAwAw9QEAAMgDACD5AQAA9gIAMAQcAAC5AwAw8wEAALoDADD1AQAAvAMAIPkBAAC9AwAwAAABAwAAoAMAIAAAAAAFCgAA_QMAIAwAAIIEACAOAAD-AwAgvwEAAL4CACDSAQAAvgIAIAUIAACgAwAgCQAAgAQAIAoAAP0DACC_AQAAvgIAIMABAAC-AgAgB6sBAQAAAAGwAUAAAAABsQFAAAAAAdkBQAAAAAHiAQEAAAAB4wEBAAAAAeQBAQAAAAEMqwEBAAAAAbABQAAAAAGxAUAAAAABvQEBAAAAAdoBAQAAAAHbAQEAAAAB3AEBAAAAAd0BAQAAAAHeAUAAAAAB3wFAAAAAAeABAQAAAAHhAQEAAAABCasBAQAAAAGtAQEAAAABsAFAAAAAAbEBQAAAAAHFAQEAAAABxwEAAADHAQLIAQIAAAAByQEBAAAAAcoBgAAAAAEGqwEBAAAAAa0BAQAAAAGuAQIAAAABrwEBAAAAAbABQAAAAAGxAUAAAAABCasBAQAAAAGwAUAAAAABsQFAAAAAAb4BAQAAAAG_AQEAAAABwAEBAAAAAcEBAQAAAAHCAQEAAAABwwEgAAAAARIFAAD1AwAgBgAA9gMAIAoAAPcDACAOAAD4AwAgDwAA-QMAIKsBAQAAAAGwAUAAAAABsQFAAAAAAb4BAQAAAAHAAQEAAAABxwEBAAAAAeUBAQAAAAHmASAAAAAB5wEBAAAAAekBAAAA6QEC6gEBAAAAAesBIAAAAAHsAQEAAAABAgAAAAEAIBwAAIgEACADAAAAKgAgHAAAiAQAIB0AAIwEACAUAAAAKgAgBQAAtAMAIAYAALUDACAKAAC2AwAgDgAAtwMAIA8AALgDACAVAACMBAAgqwEBAMQCACGwAUAAxwIAIbEBQADHAgAhvgEBAMQCACHAAQEAxgIAIccBAQDGAgAh5QEBAMQCACHmASAAzwIAIecBAQDGAgAh6QEAALID6QEi6gEBAMYCACHrASAAzwIAIewBAQDGAgAhEgUAALQDACAGAAC1AwAgCgAAtgMAIA4AALcDACAPAAC4AwAgqwEBAMQCACGwAUAAxwIAIbEBQADHAgAhvgEBAMQCACHAAQEAxgIAIccBAQDGAgAh5QEBAMQCACHmASAAzwIAIecBAQDGAgAh6QEAALID6QEi6gEBAMYCACHrASAAzwIAIewBAQDGAgAhEgQAAPQDACAGAAD2AwAgCgAA9wMAIA4AAPgDACAPAAD5AwAgqwEBAAAAAbABQAAAAAGxAUAAAAABvgEBAAAAAcABAQAAAAHHAQEAAAAB5QEBAAAAAeYBIAAAAAHnAQEAAAAB6QEAAADpAQLqAQEAAAAB6wEgAAAAAewBAQAAAAECAAAAAQAgHAAAjQQAIAMAAAAqACAcAACNBAAgHQAAkQQAIBQAAAAqACAEAACzAwAgBgAAtQMAIAoAALYDACAOAAC3AwAgDwAAuAMAIBUAAJEEACCrAQEAxAIAIbABQADHAgAhsQFAAMcCACG-AQEAxAIAIcABAQDGAgAhxwEBAMYCACHlAQEAxAIAIeYBIADPAgAh5wEBAMYCACHpAQAAsgPpASLqAQEAxgIAIesBIADPAgAh7AEBAMYCACESBAAAswMAIAYAALUDACAKAAC2AwAgDgAAtwMAIA8AALgDACCrAQEAxAIAIbABQADHAgAhsQFAAMcCACG-AQEAxAIAIcABAQDGAgAhxwEBAMYCACHlAQEAxAIAIeYBIADPAgAh5wEBAMYCACHpAQAAsgPpASLqAQEAxgIAIesBIADPAgAh7AEBAMYCACESBAAA9AMAIAUAAPUDACAKAAD3AwAgDgAA-AMAIA8AAPkDACCrAQEAAAABsAFAAAAAAbEBQAAAAAG-AQEAAAABwAEBAAAAAccBAQAAAAHlAQEAAAAB5gEgAAAAAecBAQAAAAHpAQAAAOkBAuoBAQAAAAHrASAAAAAB7AEBAAAAAQIAAAABACAcAACSBAAgAwAAACoAIBwAAJIEACAdAACWBAAgFAAAACoAIAQAALMDACAFAAC0AwAgCgAAtgMAIA4AALcDACAPAAC4AwAgFQAAlgQAIKsBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb4BAQDEAgAhwAEBAMYCACHHAQEAxgIAIeUBAQDEAgAh5gEgAM8CACHnAQEAxgIAIekBAACyA-kBIuoBAQDGAgAh6wEgAM8CACHsAQEAxgIAIRIEAACzAwAgBQAAtAMAIAoAALYDACAOAAC3AwAgDwAAuAMAIKsBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb4BAQDEAgAhwAEBAMYCACHHAQEAxgIAIeUBAQDEAgAh5gEgAM8CACHnAQEAxgIAIekBAACyA-kBIuoBAQDGAgAh6wEgAM8CACHsAQEAxgIAIQwIAACMAwAgCgAAjgMAIKsBAQAAAAGwAUAAAAABsQFAAAAAAb0BAQAAAAG-AQEAAAABvwEBAAAAAcABAQAAAAHBAQEAAAABwgEBAAAAAcMBIAAAAAECAAAAIgAgHAAAlwQAIAMAAAAgACAcAACXBAAgHQAAmwQAIA4AAAAgACAIAADQAgAgCgAA0gIAIBUAAJsEACCrAQEAxAIAIbABQADHAgAhsQFAAMcCACG9AQEAxAIAIb4BAQDEAgAhvwEBAMYCACHAAQEAxgIAIcEBAQDEAgAhwgEBAMQCACHDASAAzwIAIQwIAADQAgAgCgAA0gIAIKsBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb0BAQDEAgAhvgEBAMQCACG_AQEAxgIAIcABAQDGAgAhwQEBAMQCACHCAQEAxAIAIcMBIADPAgAhEgQAAPQDACAFAAD1AwAgBgAA9gMAIAoAAPcDACAOAAD4AwAgqwEBAAAAAbABQAAAAAGxAUAAAAABvgEBAAAAAcABAQAAAAHHAQEAAAAB5QEBAAAAAeYBIAAAAAHnAQEAAAAB6QEAAADpAQLqAQEAAAAB6wEgAAAAAewBAQAAAAECAAAAAQAgHAAAnAQAIAwIAACMAwAgCQAAjQMAIKsBAQAAAAGwAUAAAAABsQFAAAAAAb0BAQAAAAG-AQEAAAABvwEBAAAAAcABAQAAAAHBAQEAAAABwgEBAAAAAcMBIAAAAAECAAAAIgAgHAAAngQAIAMAAAAgACAcAACeBAAgHQAAogQAIA4AAAAgACAIAADQAgAgCQAA0QIAIBUAAKIEACCrAQEAxAIAIbABQADHAgAhsQFAAMcCACG9AQEAxAIAIb4BAQDEAgAhvwEBAMYCACHAAQEAxgIAIcEBAQDEAgAhwgEBAMQCACHDASAAzwIAIQwIAADQAgAgCQAA0QIAIKsBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb0BAQDEAgAhvgEBAMQCACG_AQEAxgIAIcABAQDGAgAhwQEBAMQCACHCAQEAxAIAIcMBIADPAgAhCasBAQAAAAGwAUAAAAABsQFAAAAAAcQBAQAAAAHFAQEAAAABxwEAAADHAQLIAQIAAAAByQEBAAAAAcoBgAAAAAEGqwEBAAAAAawBAQAAAAGuAQIAAAABrwEBAAAAAbABQAAAAAGxAUAAAAABCasBAQAAAAGwAUAAAAABsQFAAAAAAb4BAQAAAAG_AQEAAAAB0QECAAAAAdIBAQAAAAHTASAAAAAB1QEAAADVAQIMDAAAmgMAIA4AAIsDACCrAQEAAAABsAFAAAAAAbEBQAAAAAG-AQEAAAABvwEBAAAAAcUBAQAAAAHRAQIAAAAB0gEBAAAAAdMBIAAAAAHVAQAAANUBAgIAAAATACAcAACmBAAgEgQAAPQDACAFAAD1AwAgBgAA9gMAIA4AAPgDACAPAAD5AwAgqwEBAAAAAbABQAAAAAGxAUAAAAABvgEBAAAAAcABAQAAAAHHAQEAAAAB5QEBAAAAAeYBIAAAAAHnAQEAAAAB6QEAAADpAQLqAQEAAAAB6wEgAAAAAewBAQAAAAECAAAAAQAgHAAAqAQAIAMAAAARACAcAACmBAAgHQAArAQAIA4AAAARACAMAACZAwAgDgAA8QIAIBUAAKwEACCrAQEAxAIAIbABQADHAgAhsQFAAMcCACG-AQEAxAIAIb8BAQDGAgAhxQEBAMQCACHRAQIAxQIAIdIBAQDGAgAh0wEgAM8CACHVAQAA7gLVASIMDAAAmQMAIA4AAPECACCrAQEAxAIAIbABQADHAgAhsQFAAMcCACG-AQEAxAIAIb8BAQDGAgAhxQEBAMQCACHRAQIAxQIAIdIBAQDGAgAh0wEgAM8CACHVAQAA7gLVASIDAAAAKgAgHAAAqAQAIB0AAK8EACAUAAAAKgAgBAAAswMAIAUAALQDACAGAAC1AwAgDgAAtwMAIA8AALgDACAVAACvBAAgqwEBAMQCACGwAUAAxwIAIbEBQADHAgAhvgEBAMQCACHAAQEAxgIAIccBAQDGAgAh5QEBAMQCACHmASAAzwIAIecBAQDGAgAh6QEAALID6QEi6gEBAMYCACHrASAAzwIAIewBAQDGAgAhEgQAALMDACAFAAC0AwAgBgAAtQMAIA4AALcDACAPAAC4AwAgqwEBAMQCACGwAUAAxwIAIbEBQADHAgAhvgEBAMQCACHAAQEAxgIAIccBAQDGAgAh5QEBAMQCACHmASAAzwIAIecBAQDGAgAh6QEAALID6QEi6gEBAMYCACHrASAAzwIAIewBAQDGAgAhCasBAQAAAAGtAQEAAAABsAFAAAAAAbEBQAAAAAHEAQEAAAABxwEAAADHAQLIAQIAAAAByQEBAAAAAcoBgAAAAAEDAAAAKgAgHAAAnAQAIB0AALMEACAUAAAAKgAgBAAAswMAIAUAALQDACAGAAC1AwAgCgAAtgMAIA4AALcDACAVAACzBAAgqwEBAMQCACGwAUAAxwIAIbEBQADHAgAhvgEBAMQCACHAAQEAxgIAIccBAQDGAgAh5QEBAMQCACHmASAAzwIAIecBAQDGAgAh6QEAALID6QEi6gEBAMYCACHrASAAzwIAIewBAQDGAgAhEgQAALMDACAFAAC0AwAgBgAAtQMAIAoAALYDACAOAAC3AwAgqwEBAMQCACGwAUAAxwIAIbEBQADHAgAhvgEBAMQCACHAAQEAxgIAIccBAQDGAgAh5QEBAMQCACHmASAAzwIAIecBAQDGAgAh6QEAALID6QEi6gEBAMYCACHrASAAzwIAIewBAQDGAgAhDAoAAIoDACAMAACaAwAgqwEBAAAAAbABQAAAAAGxAUAAAAABvgEBAAAAAb8BAQAAAAHFAQEAAAAB0QECAAAAAdIBAQAAAAHTASAAAAAB1QEAAADVAQICAAAAEwAgHAAAtAQAIBIEAAD0AwAgBQAA9QMAIAYAAPYDACAKAAD3AwAgDwAA-QMAIKsBAQAAAAGwAUAAAAABsQFAAAAAAb4BAQAAAAHAAQEAAAABxwEBAAAAAeUBAQAAAAHmASAAAAAB5wEBAAAAAekBAAAA6QEC6gEBAAAAAesBIAAAAAHsAQEAAAABAgAAAAEAIBwAALYEACADAAAAEQAgHAAAtAQAIB0AALoEACAOAAAAEQAgCgAA8AIAIAwAAJkDACAVAAC6BAAgqwEBAMQCACGwAUAAxwIAIbEBQADHAgAhvgEBAMQCACG_AQEAxgIAIcUBAQDEAgAh0QECAMUCACHSAQEAxgIAIdMBIADPAgAh1QEAAO4C1QEiDAoAAPACACAMAACZAwAgqwEBAMQCACGwAUAAxwIAIbEBQADHAgAhvgEBAMQCACG_AQEAxgIAIcUBAQDEAgAh0QECAMUCACHSAQEAxgIAIdMBIADPAgAh1QEAAO4C1QEiAwAAACoAIBwAALYEACAdAAC9BAAgFAAAACoAIAQAALMDACAFAAC0AwAgBgAAtQMAIAoAALYDACAPAAC4AwAgFQAAvQQAIKsBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb4BAQDEAgAhwAEBAMYCACHHAQEAxgIAIeUBAQDEAgAh5gEgAM8CACHnAQEAxgIAIekBAACyA-kBIuoBAQDGAgAh6wEgAM8CACHsAQEAxgIAIRIEAACzAwAgBQAAtAMAIAYAALUDACAKAAC2AwAgDwAAuAMAIKsBAQDEAgAhsAFAAMcCACGxAUAAxwIAIb4BAQDEAgAhwAEBAMYCACHHAQEAxgIAIeUBAQDEAgAh5gEgAM8CACHnAQEAxgIAIekBAACyA-kBIuoBAQDGAgAh6wEgAM8CACHsAQEAxgIAIQcEBgIFCgMGDAQKEAULAAsOHwkPIwcBAwABAQMAAQEDAAEDBwABDAAHDQAGBAoYBQsACgwABw4cCQQIAAEJFAYKFQULAAgCCRYAChcAAgMAAQ0ABgIKHQAOHgAFBCQABSUACiYADicADygAAAAAAwsAECIAESMAEgAAAAMLABAiABEjABIBAwABAQMAAQMLABciABgjABkAAAADCwAXIgAYIwAZAQMAAQEDAAEDCwAeIgAfIwAgAAAAAwsAHiIAHyMAIAAAAAMLACYiACcjACgAAAADCwAmIgAnIwAoAQMAAQEDAAEDCwAtIgAuIwAvAAAAAwsALSIALiMALwEMAAcBDAAHBQsANCIANyMAOHQANXUANgAAAAAABQsANCIANyMAOHQANXUANgMHAAEMAAcNAAYDBwABDAAHDQAGBQsAPSIAQCMAQXQAPnUAPwAAAAAABQsAPSIAQCMAQXQAPnUAPwEIAAEBCAABAwsARiIARyMASAAAAAMLAEYiAEcjAEgCAwABDQAGAgMAAQ0ABgULAE0iAFAjAFF0AE51AE8AAAAAAAULAE0iAFAjAFF0AE51AE8QAgERKQESLAETLQEULgEWMAEXMgwYMw0ZNQEaNwwbOA4eOQEfOgEgOwwkPg8lPxMmQAInQQIoQgIpQwIqRAIrRgIsSAwtSRQuSwIvTQwwThUxTwIyUAIzUQw0VBY1VRo2VgM3VwM4WAM5WQM6WgM7XAM8Xgw9Xxs-YQM_YwxAZBxBZQNCZgNDZwxEah1FayFGbSJHbiJIcSJJciJKcyJLdSJMdwxNeCNOeiJPfAxQfSRRfiJSfyJTgAEMVIMBJVWEASlWhgEEV4cBBFiJAQRZigEEWosBBFuNAQRcjwEMXZABKl6SAQRflAEMYJUBK2GWAQRilwEEY5gBDGSbASxlnAEwZp0BBmeeAQZonwEGaaABBmqhAQZrowEGbKUBDG2mATFuqAEGb6oBDHCrATJxrAEGcq0BBnOuAQx2sQEzd7IBOXizAQV5tAEFerUBBXu2AQV8twEFfbkBBX67AQx_vAE6gAG-AQWBAcABDIIBwQE7gwHCAQWEAcMBBYUBxAEMhgHHATyHAcgBQogByQEHiQHKAQeKAcsBB4sBzAEHjAHNAQeNAc8BB44B0QEMjwHSAUOQAdQBB5EB1gEMkgHXAUSTAdgBB5QB2QEHlQHaAQyWAd0BRZcB3gFJmAHfAQmZAeABCZoB4QEJmwHiAQmcAeMBCZ0B5QEJngHnAQyfAegBSqAB6gEJoQHsAQyiAe0BS6MB7gEJpAHvAQmlAfABDKYB8wFMpwH0AVI"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer: Buffer2 } = await import("buffer");
  const wasmArray = Buffer2.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
var prismaNamespace_exports = {};
__export(prismaNamespace_exports, {
  AccountScalarFieldEnum: () => AccountScalarFieldEnum,
  AnyNull: () => AnyNull2,
  CartScalarFieldEnum: () => CartScalarFieldEnum,
  DbNull: () => DbNull2,
  Decimal: () => Decimal2,
  JsonNull: () => JsonNull2,
  JsonNullValueFilter: () => JsonNullValueFilter,
  JsonNullValueInput: () => JsonNullValueInput,
  MenuItemScalarFieldEnum: () => MenuItemScalarFieldEnum,
  ModelName: () => ModelName,
  NullTypes: () => NullTypes2,
  NullableJsonNullValueInput: () => NullableJsonNullValueInput,
  NullsOrder: () => NullsOrder,
  OrderScalarFieldEnum: () => OrderScalarFieldEnum,
  PrismaClientInitializationError: () => PrismaClientInitializationError2,
  PrismaClientKnownRequestError: () => PrismaClientKnownRequestError2,
  PrismaClientRustPanicError: () => PrismaClientRustPanicError2,
  PrismaClientUnknownRequestError: () => PrismaClientUnknownRequestError2,
  PrismaClientValidationError: () => PrismaClientValidationError2,
  QueryMode: () => QueryMode,
  RestaurantScalarFieldEnum: () => RestaurantScalarFieldEnum,
  ReviewScalarFieldEnum: () => ReviewScalarFieldEnum,
  SessionScalarFieldEnum: () => SessionScalarFieldEnum,
  SortOrder: () => SortOrder,
  Sql: () => Sql2,
  TransactionIsolationLevel: () => TransactionIsolationLevel,
  UserScalarFieldEnum: () => UserScalarFieldEnum,
  VerificationScalarFieldEnum: () => VerificationScalarFieldEnum,
  defineExtension: () => defineExtension,
  empty: () => empty2,
  getExtensionContext: () => getExtensionContext,
  join: () => join2,
  prismaVersion: () => prismaVersion,
  raw: () => raw2,
  sql: () => sql
});
import * as runtime2 from "@prisma/client/runtime/client";
var PrismaClientKnownRequestError2 = runtime2.PrismaClientKnownRequestError;
var PrismaClientUnknownRequestError2 = runtime2.PrismaClientUnknownRequestError;
var PrismaClientRustPanicError2 = runtime2.PrismaClientRustPanicError;
var PrismaClientInitializationError2 = runtime2.PrismaClientInitializationError;
var PrismaClientValidationError2 = runtime2.PrismaClientValidationError;
var sql = runtime2.sqltag;
var empty2 = runtime2.empty;
var join2 = runtime2.join;
var raw2 = runtime2.raw;
var Sql2 = runtime2.Sql;
var Decimal2 = runtime2.Decimal;
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var prismaVersion = {
  client: "7.5.0",
  engine: "280c870be64f457428992c43c1f6d557fab6e29e"
};
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var DbNull2 = runtime2.DbNull;
var JsonNull2 = runtime2.JsonNull;
var AnyNull2 = runtime2.AnyNull;
var ModelName = {
  User: "User",
  Session: "Session",
  Account: "Account",
  Verification: "Verification",
  Cart: "Cart",
  MenuItem: "MenuItem",
  Order: "Order",
  Restaurant: "Restaurant",
  Review: "Review"
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var UserScalarFieldEnum = {
  id: "id",
  name: "name",
  email: "email",
  emailVerified: "emailVerified",
  image: "image",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  role: "role",
  phone: "phone",
  status: "status",
  businessName: "businessName",
  isApproved: "isApproved",
  addresses: "addresses"
};
var SessionScalarFieldEnum = {
  id: "id",
  expiresAt: "expiresAt",
  token: "token",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  ipAddress: "ipAddress",
  userAgent: "userAgent",
  userId: "userId"
};
var AccountScalarFieldEnum = {
  id: "id",
  accountId: "accountId",
  providerId: "providerId",
  userId: "userId",
  accessToken: "accessToken",
  refreshToken: "refreshToken",
  idToken: "idToken",
  accessTokenExpiresAt: "accessTokenExpiresAt",
  refreshTokenExpiresAt: "refreshTokenExpiresAt",
  scope: "scope",
  password: "password",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var VerificationScalarFieldEnum = {
  id: "id",
  identifier: "identifier",
  value: "value",
  expiresAt: "expiresAt",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var CartScalarFieldEnum = {
  id: "id",
  userId: "userId",
  items: "items",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var MenuItemScalarFieldEnum = {
  id: "id",
  restaurantId: "restaurantId",
  name: "name",
  description: "description",
  priceCents: "priceCents",
  imageUrl: "imageUrl",
  isAvailable: "isAvailable",
  cuisine: "cuisine",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var OrderScalarFieldEnum = {
  id: "id",
  customerId: "customerId",
  menuItemId: "menuItemId",
  restaurantId: "restaurantId",
  status: "status",
  totalCents: "totalCents",
  notes: "notes",
  deliveryAddressSnapshot: "deliveryAddressSnapshot",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var RestaurantScalarFieldEnum = {
  id: "id",
  providerId: "providerId",
  name: "name",
  description: "description",
  phone: "phone",
  addressLine: "addressLine",
  city: "city",
  isActive: "isActive",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var ReviewScalarFieldEnum = {
  id: "id",
  userId: "userId",
  menuItemId: "menuItemId",
  rating: "rating",
  comment: "comment",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var SortOrder = {
  asc: "asc",
  desc: "desc"
};
var JsonNullValueInput = {
  JsonNull: JsonNull2
};
var NullableJsonNullValueInput = {
  DbNull: DbNull2,
  JsonNull: JsonNull2
};
var QueryMode = {
  default: "default",
  insensitive: "insensitive"
};
var NullsOrder = {
  first: "first",
  last: "last"
};
var JsonNullValueFilter = {
  DbNull: DbNull2,
  JsonNull: JsonNull2,
  AnyNull: AnyNull2
};
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/enums.ts
var OrderStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  PREPARING: "PREPARING",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED"
};

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/modules/menuItem/menuItem.service.ts
var createMenuItem = async (userId, data) => {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { role: true, status: true }
  });
  if (!user) {
    const err = new Error("User not found.");
    err.statusCode = 404;
    throw err;
  }
  if (user.role !== "PROVIDER") {
    const err = new Error("Only providers can create menu items.");
    err.statusCode = 403;
    throw err;
  }
  if (user.status === "SUSPENDED") {
    const err = new Error("User is not SUSPENDED.");
    err.statusCode = 403;
    throw err;
  }
  const restaurant = await prisma.restaurant.findFirst({
    where: { providerId: userId },
    select: { id: true }
  });
  if (!restaurant) {
    const err = new Error("Restaurant not found or you don't own it.");
    err.statusCode = 404;
    throw err;
  }
  const result = await prisma.menuItem.create({
    data: {
      restaurantId: restaurant.id,
      name: data.name,
      description: data.description ?? null,
      priceCents: data.priceCents,
      imageUrl: data.imageUrl ?? null,
      isAvailable: data.isAvailable ?? true,
      cuisine: data.cuisine
    }
  });
  return result;
};
var getAllMenuItems = async ({ cuisine, minPrice } = {}) => {
  const where = {
    isAvailable: true
  };
  if (cuisine) {
    where.cuisine = cuisine;
  }
  if (typeof minPrice === "number") {
    where.priceCents = { gte: minPrice };
  }
  return prisma.menuItem.findMany({
    where,
    orderBy: { createdAt: "desc" }
  });
};
var getMenuItemById = async (id) => {
  const result = await prisma.menuItem.findUnique({
    where: {
      id
    }
  });
  return result;
};
var getMenuItemByRestaurantId = async (id) => {
  const result = await prisma.menuItem.findMany({
    where: {
      restaurantId: id
    }
  });
  return result;
};
var updateMenuItem = async (providerId, menuItemId, data) => {
  const existing = await prisma.menuItem.findFirst({
    where: {
      id: menuItemId,
      restaurant: {
        providerId
      }
    },
    select: { id: true }
  });
  if (!existing) {
    const err = new Error("Menu item not found or you don't have access.");
    err.statusCode = 404;
    throw err;
  }
  if (data.priceCents !== void 0) {
    if (!Number.isInteger(data.priceCents) || data.priceCents <= 0) {
      const err = new Error("priceCents must be a positive integer.");
      err.statusCode = 400;
      throw err;
    }
  }
  return prisma.menuItem.update({
    where: { id: menuItemId },
    data: {
      ...data.name !== void 0 ? { name: data.name } : {},
      ...data.description !== void 0 ? { description: data.description } : {},
      ...data.priceCents !== void 0 ? { priceCents: data.priceCents } : {},
      ...data.imageUrl !== void 0 ? { imageUrl: data.imageUrl } : {},
      ...data.isAvailable !== void 0 ? { isAvailable: data.isAvailable } : {},
      ...data.cuisine !== void 0 ? { cuisine: data.cuisine } : {}
    }
  });
};
var deleteMenuItem = async (providerId, menuItemId) => {
  const existing = await prisma.menuItem.findFirst({
    where: { id: menuItemId, restaurant: { providerId } },
    select: { id: true }
  });
  if (!existing) {
    const err = new Error("Menu item not found or you don't have access.");
    err.statusCode = 404;
    throw err;
  }
  return prisma.menuItem.delete({ where: { id: menuItemId } });
};
var menuItemService = {
  createMenuItem,
  getAllMenuItems,
  getMenuItemById,
  getMenuItemByRestaurantId,
  updateMenuItem,
  deleteMenuItem
};

// src/modules/menuItem/menuItem.controller.ts
var CUISINES = ["MEAT", "FISH", "VEG", "VEGAN"];
var createMenuItem2 = async (req, res, next) => {
  try {
    if (!req.user?.id) {
      return res.status(400).json({
        success: false,
        message: "Authentication required!"
      });
    }
    const result = await menuItemService.createMenuItem(req.user.id, req.body);
    return res.status(201).json({
      success: true,
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getAllMenuItems2 = async (req, res, next) => {
  try {
    const cuisineRaw = req.query.cuisine;
    const minPriceRaw = req.query.minPrice;
    const cuisine = typeof cuisineRaw === "string" && CUISINES.includes(cuisineRaw) ? cuisineRaw : void 0;
    const minPrice = typeof minPriceRaw === "string" && !Number.isNaN(Number(minPriceRaw)) ? Number(minPriceRaw) : void 0;
    const result = await menuItemService.getAllMenuItems({
      cuisine,
      minPrice
    });
    res.status(200).json(result);
  } catch (err) {
    next(err);
  }
};
var getMenuItemById2 = async (req, res, next) => {
  try {
    const { menuItemId } = req.params;
    const result = await menuItemService.getMenuItemById(menuItemId);
    res.status(200).json(result);
  } catch (err) {
    next(err);
  }
};
var getMenuItemByRestaurantId2 = async (req, res, next) => {
  try {
    const { restaurantId } = req.params;
    const result = await menuItemService.getMenuItemByRestaurantId(restaurantId);
    res.status(200).json(result);
  } catch (err) {
    next(err);
  }
};
var updateMenuItem2 = async (req, res, next) => {
  try {
    const providerId = req.user.id;
    const { menuItemId } = req.params;
    const result = await menuItemService.updateMenuItem(providerId, menuItemId, req.body);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var deleteMenuItem2 = async (req, res, next) => {
  try {
    const providerId = req.user.id;
    const { menuItemId } = req.params;
    const result = await menuItemService.deleteMenuItem(providerId, menuItemId);
    res.status(200).json({
      success: true,
      message: "Menu item deleted.",
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var MenuItemController = {
  createMenuItem: createMenuItem2,
  getAllMenuItems: getAllMenuItems2,
  getMenuItemById: getMenuItemById2,
  getMenuItemByRestaurantId: getMenuItemByRestaurantId2,
  updateMenuItem: updateMenuItem2,
  deleteMenuItem: deleteMenuItem2
};

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
var trustedOriginsList = [
  process.env.APP_URL,
  // Local development
  process.env.PROD_APP_URL,
  // Production frontend
  process.env.FRONTEND_URL
  // Additional frontend URL
].filter(Boolean);
if (process.env.VERCEL_ENV === "preview" || process.env.VERCEL_ENV === "production") {
  trustedOriginsList.push("https://*.vercel.app");
}
var auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: "postgresql"
    // or "mysql", "postgresql", ...etcc
  }),
  trustedOrigins: trustedOriginsList,
  user: {
    additionalFields: {
      role: {
        type: "string",
        defaultValue: "CUSTOMER",
        required: false
      },
      phone: {
        type: "string",
        required: false
      },
      status: {
        type: "string",
        defaultValue: "ACTIVE",
        required: false
      },
      businessName: {
        type: "string",
        required: false
      },
      isApproved: {
        type: "boolean",
        defaultValue: true,
        required: false
      },
      addresses: {
        type: "string",
        required: false
      }
    }
  },
  emailAndPassword: {
    enabled: true,
    autoSignIn: false,
    requireEmailVerification: false
  },
  socialProviders: {
    google: {
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      accessType: "offline",
      prompt: "select_account consent"
    }
  },
  // session: {
  //     cookieCache: {
  //         enabled: true,
  //         maxAge: 5 * 60, // 5 minutes
  //     },
  // },
  // advanced: {
  //     cookiePrefix: "better-auth",
  //     useSecureCookies: process.env.NODE_ENV === "production",
  //     sameSiteCookie: "none", // Allow cross-domain cookies for Vercel deployments
  //     crossSubDomainCookies: {
  //         enabled: true, // Enable for cross-domain cookie handling
  //     },
  //     disableCSRFCheck: true, // Allow requests without Origin header (Postman, mobile apps, etc.)
  // },
  session: {
    cookieCache: {
      enabled: true,
      maxAge: 5 * 60
      // 5 minutes
    }
  },
  advanced: {
    cookiePrefix: "better-auth",
    useSecureCookies: process.env.NODE_ENV === "production",
    crossSubDomainCookies: {
      enabled: false
    },
    disableCSRFCheck: true
    // Allow requests without Origin header (Postman, mobile apps, etc.)
  }
});

// src/middlewares/auth.middleware.ts
var auth2 = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: req.headers
      });
      if (!session || !session.user) {
        return res.status(401).json({
          success: false,
          message: "Authentication required."
        });
      }
      const role = session.user.role;
      if (!role) {
        return res.status(403).json({
          success: false,
          message: "User role not assigned."
        });
      }
      const dbUser = await prisma.user.findUnique({
        where: { id: session.user.id },
        select: { status: true }
      });
      req.user = {
        id: session.user.id,
        email: session.user.email,
        name: session.user.name,
        role,
        status: dbUser?.status
      };
      if (roles.length && !roles.includes(role)) {
        return res.status(403).json({
          success: false,
          message: "You do not have permission to access this resource."
        });
      }
      next();
    } catch (error) {
      next(error);
    }
  };
};

// src/modules/menuItem/menuItem.router.ts
var router = express.Router();
router.get("/", MenuItemController.getAllMenuItems);
router.get("/restaurant/:restaurantId", MenuItemController.getMenuItemByRestaurantId);
router.get("/:menuItemId", MenuItemController.getMenuItemById);
router.post("/", auth2("PROVIDER" /* PROVIDER */), MenuItemController.createMenuItem);
router.patch("/:menuItemId", auth2("PROVIDER" /* PROVIDER */), MenuItemController.updateMenuItem);
router.delete("/:menuItemId", auth2("PROVIDER" /* PROVIDER */), MenuItemController.deleteMenuItem);
var menuItemsRouter = router;

// src/modules/restaurant/restaurant.router.ts
import express2 from "express";

// src/modules/restaurant/restaurant.service.ts
var createRestaurant = async (data, userId) => {
  const isRestaurantExist = await prisma.restaurant.findFirst({
    where: {
      providerId: userId
    }
  });
  if (isRestaurantExist) {
    throw new Error("You Already have a restaurant ");
  }
  const result = await prisma.restaurant.create({
    data: {
      ...data,
      providerId: userId
    }
  });
  return result;
};
var getAllRestaurants = async () => {
  return prisma.restaurant.findMany({
    where: {
      isActive: true
    },
    orderBy: {
      createdAt: "desc"
    }
  });
};
var getRestaurantById = async (id) => {
  const result = await prisma.restaurant.findUnique({
    where: {
      id
    }
  });
  return result;
};
var getRestaurantByProviderId = async (id) => {
  const result = await prisma.restaurant.findFirst({
    where: {
      providerId: id
    }
  });
  return result;
};
var updateRestaurant = async (restaurantId, providerId, data) => {
  if (!restaurantId) {
    const err = new Error("restaurantId is required.");
    err.statusCode = 400;
    throw err;
  }
  const user = await prisma.user.findUnique({
    where: { id: providerId },
    select: { role: true, status: true }
  });
  if (!user) {
    const err = new Error("User not found.");
    err.statusCode = 404;
    throw err;
  }
  if (user.role !== "PROVIDER") {
    const err = new Error("Only providers can update restaurant.");
    err.statusCode = 403;
    throw err;
  }
  if ((user.status || "").toUpperCase() === "SUSPENDED") {
    const err = new Error("You are SUSPENDED. You cannot update restaurant.");
    err.statusCode = 403;
    throw err;
  }
  const existing = await prisma.restaurant.findFirst({
    where: {
      id: restaurantId,
      providerId
    },
    select: { id: true }
  });
  if (!existing) {
    const err = new Error("Restaurant not found or you don't have access.");
    err.statusCode = 404;
    throw err;
  }
  const allowedData = {};
  if (data.name !== void 0) {
    const name = data.name.trim();
    if (!name) {
      const err = new Error("name cannot be empty.");
      err.statusCode = 400;
      throw err;
    }
    allowedData.name = name;
  }
  if (data.description !== void 0) {
    allowedData.description = data.description === null ? null : data.description.trim() || null;
  }
  if (data.phone !== void 0) {
    allowedData.phone = data.phone === null ? null : data.phone.trim() || null;
  }
  if (data.addressLine !== void 0) {
    const addressLine = data.addressLine.trim();
    if (!addressLine) {
      const err = new Error("addressLine cannot be empty.");
      err.statusCode = 400;
      throw err;
    }
    allowedData.addressLine = addressLine;
  }
  if (data.city !== void 0) {
    const city = data.city.trim();
    if (!city) {
      const err = new Error("city cannot be empty.");
      err.statusCode = 400;
      throw err;
    }
    allowedData.city = city;
  }
  if (data.isActive !== void 0) {
    if (typeof data.isActive !== "boolean") {
      const err = new Error("isActive must be boolean.");
      err.statusCode = 400;
      throw err;
    }
    allowedData.isActive = data.isActive;
  }
  if (Object.keys(allowedData).length === 0) {
    const err = new Error("No valid fields provided for update.");
    err.statusCode = 400;
    throw err;
  }
  return prisma.restaurant.update({
    where: { id: restaurantId },
    data: allowedData,
    select: {
      id: true,
      providerId: true,
      name: true,
      description: true,
      phone: true,
      addressLine: true,
      city: true,
      isActive: true,
      createdAt: true,
      updatedAt: true
    }
  });
};
var restaurantService = {
  createRestaurant,
  getAllRestaurants,
  getRestaurantById,
  updateRestaurant,
  getRestaurantByProviderId
};

// src/modules/restaurant/restaurant.controller.ts
var createRestaurant2 = async (req, res, next) => {
  try {
    if (!req.user?.id) {
      return res.status(400).json({
        success: false,
        message: "Unauthorized!"
      });
    }
    const result = await restaurantService.createRestaurant(req.body, req.user.id);
    res.status(201).json(result);
  } catch (error) {
    next(error);
  }
};
var getRestaurants = async (req, res, next) => {
  try {
    const result = await restaurantService.getAllRestaurants();
    res.status(200).json(result);
  } catch (err) {
    next(err);
  }
};
var getRestaurantById2 = async (req, res, next) => {
  try {
    const { restaurantId } = req.params;
    const result = await restaurantService.getRestaurantById(restaurantId);
    res.status(200).json(result);
  } catch (err) {
    next(err);
  }
};
var getRestaurantByProviderId2 = async (req, res, next) => {
  try {
    const { providerId } = req.params;
    const result = await restaurantService.getRestaurantByProviderId(providerId);
    res.status(200).json(result);
  } catch (err) {
    next(err);
  }
};
var updateRestaurant2 = async (req, res, next) => {
  try {
    if (!req.user?.id) {
      return res.status(401).json({
        success: false,
        message: "Unauthorized!"
      });
    }
    const { restaurantId } = req.params;
    const result = await restaurantService.updateRestaurant(
      restaurantId,
      req.user.id,
      req.body
    );
    res.status(200).json({
      success: true,
      message: "Restaurant updated.",
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var RestaurantController = {
  createRestaurant: createRestaurant2,
  getRestaurants,
  getRestaurantById: getRestaurantById2,
  updateRestaurant: updateRestaurant2,
  getRestaurantByProviderId: getRestaurantByProviderId2
};

// src/modules/restaurant/restaurant.router.ts
var router2 = express2.Router();
router2.get("/", RestaurantController.getRestaurants);
router2.get("/provider/:providerId", auth2("PROVIDER" /* PROVIDER */), RestaurantController.getRestaurantByProviderId);
router2.get("/:restaurantId", RestaurantController.getRestaurantById);
router2.patch("/:restaurantId", auth2("PROVIDER" /* PROVIDER */), RestaurantController.updateRestaurant);
router2.post("/", auth2("PROVIDER" /* PROVIDER */), RestaurantController.createRestaurant);
var restaurantRouter = router2;

// src/middlewares/globalErrorEandler.ts
function errorHandler(err, req, res, next) {
  if (res.headersSent) return next(err);
  let statusCode = 500;
  let errorMessage = "Internal Server Error";
  if (typeof err?.statusCode === "number") {
    statusCode = err.statusCode;
    errorMessage = err.message || errorMessage;
  }
  if (err instanceof prismaNamespace_exports.PrismaClientValidationError) {
    statusCode = 400;
    errorMessage = "You have provided invalid field type or missing field.";
  } else if (err instanceof prismaNamespace_exports.PrismaClientKnownRequestError) {
    if (err.code === "P2025") {
      statusCode = 404;
      errorMessage = "Record not found.";
    } else if (err.code === "P2002") {
      statusCode = 409;
      errorMessage = "Duplicate key error.";
    } else if (err.code === "P2003") {
      statusCode = 400;
      errorMessage = "Foreign key constraint failed.";
    }
  } else if (err instanceof prismaNamespace_exports.PrismaClientUnknownRequestError) {
    statusCode = 500;
    errorMessage = "Error occurred during query execution.";
  } else if (err instanceof prismaNamespace_exports.PrismaClientInitializationError) {
    if (err.errorCode === "P1000") {
      statusCode = 401;
      errorMessage = "Authentication failed. Please check your credentials.";
    } else if (err.errorCode === "P1001") {
      statusCode = 503;
      errorMessage = "Can't reach database server.";
    }
  }
  return res.status(statusCode).json({
    success: false,
    message: errorMessage,
    error: process.env.NODE_ENV === "production" ? void 0 : err
  });
}
var globalErrorEandler_default = errorHandler;

// src/modules/cart/cart.router.ts
import { Router } from "express";

// src/modules/cart/cart.service.ts
var addToCart = async (userId, data) => {
  const { menuItemId } = data;
  const quantity = data.quantity ?? 1;
  if (!menuItemId) {
    const err = new Error("menuItemId is required.");
    err.statusCode = 400;
    throw err;
  }
  if (!Number.isInteger(quantity) || quantity <= 0) {
    const err = new Error("quantity must be a positive integer.");
    err.statusCode = 400;
    throw err;
  }
  const menuItem = await prisma.menuItem.findUnique({
    where: { id: menuItemId },
    select: { id: true, isAvailable: true }
  });
  if (!menuItem || !menuItem.isAvailable) {
    const err = new Error("Menu item not available.");
    err.statusCode = 400;
    throw err;
  }
  let cart = await prisma.cart.findUnique({
    where: { userId }
  });
  if (!cart) {
    cart = await prisma.cart.create({
      data: {
        userId,
        items: [{ menuItemId, quantity }]
      }
    });
    return cart;
  }
  const items = cart.items ?? [];
  const existing = items.find((i) => i.menuItemId === menuItemId);
  if (existing) {
    existing.quantity += quantity;
  } else {
    items.push({ menuItemId, quantity });
  }
  return prisma.cart.update({
    where: { userId },
    data: { items }
  });
};
var getMyCart = async (userId) => {
  return prisma.cart.findUnique({
    where: { userId }
  });
};
var clearCart = async (userId) => {
  return prisma.cart.update({
    where: { userId },
    data: { items: [] }
  });
};
var removeCartItemByMenuId = async (userId, menuItemId) => {
  if (!menuItemId) {
    const err = new Error("menuItemId is required.");
    err.statusCode = 400;
    throw err;
  }
  const cart = await prisma.cart.findUnique({
    where: { userId }
  });
  if (!cart) {
    const err = new Error("Cart not found.");
    err.statusCode = 404;
    throw err;
  }
  const items = (cart.items ?? []).filter((i) => i.menuItemId !== menuItemId);
  if ((cart.items ?? []).length === items.length) {
    const err = new Error("Item not found in cart.");
    err.statusCode = 404;
    throw err;
  }
  const updated = await prisma.cart.update({
    where: { userId },
    data: { items }
  });
  return updated;
};
var cartService = {
  addToCart,
  getMyCart,
  clearCart,
  removeCartItemByMenuId
};

// src/modules/cart/cart.controller.ts
var addToCart2 = async (req, res, next) => {
  try {
    const userId = req.user.id;
    const result = await cartService.addToCart(userId, req.body);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var getMyCart2 = async (req, res, next) => {
  try {
    const userId = req.user.id;
    const result = await cartService.getMyCart(userId);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var clearCart2 = async (req, res, next) => {
  try {
    const userId = req.user.id;
    await cartService.clearCart(userId);
    res.status(200).json({
      success: true,
      message: "Cart cleared."
    });
  } catch (err) {
    next(err);
  }
};
var removeCartItemByMenuId2 = async (req, res, next) => {
  try {
    const userId = req.user.id;
    const { menuItemId } = req.params;
    const result = await cartService.removeCartItemByMenuId(userId, menuItemId);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var CartController = {
  addToCart: addToCart2,
  getMyCart: getMyCart2,
  clearCart: clearCart2,
  removeCartItemByMenuId: removeCartItemByMenuId2
};

// src/modules/cart/cart.router.ts
var router3 = Router();
router3.post("/add", auth2("CUSTOMER" /* CUSTOMER */), CartController.addToCart);
router3.get("/", auth2("CUSTOMER" /* CUSTOMER */), CartController.getMyCart);
router3.delete("/item/:menuItemId", auth2("CUSTOMER" /* CUSTOMER */), CartController.removeCartItemByMenuId);
router3.delete("/clear", auth2("CUSTOMER" /* CUSTOMER */), CartController.clearCart);
var cartRouter = router3;

// src/modules/order/order.router.ts
import { Router as Router2 } from "express";

// src/modules/order/order.service.ts
var getallOrders = async () => {
  return prisma.order.findMany({
    orderBy: {
      createdAt: "desc"
    }
  });
};
var checkoutFromCart = async (customerId, input) => {
  if (!input?.deliveryAddressSnapshot) {
    const err = new Error("deliveryAddressSnapshot is required for delivery (Cash on Delivery).");
    err.statusCode = 400;
    throw err;
  }
  const cart = await prisma.cart.findUnique({
    where: { userId: customerId },
    select: { id: true, items: true }
  });
  if (!cart) {
    const err = new Error("Cart not found.");
    err.statusCode = 404;
    throw err;
  }
  const cartItems = cart.items ?? [];
  if (cartItems.length === 0) {
    const err = new Error("Cart is empty.");
    err.statusCode = 400;
    throw err;
  }
  for (const item of cartItems) {
    if (!item.menuItemId || !Number.isInteger(item.quantity) || item.quantity <= 0) {
      const err = new Error("Cart contains invalid items.");
      err.statusCode = 400;
      throw err;
    }
  }
  const menuItemIds = cartItems.map((i) => i.menuItemId);
  const menuItems = await prisma.menuItem.findMany({
    where: { id: { in: menuItemIds } },
    select: {
      id: true,
      priceCents: true,
      isAvailable: true,
      restaurantId: true,
      restaurant: { select: { isActive: true } }
    }
  });
  const map = new Map(menuItems.map((m) => [m.id, m]));
  for (const item of cartItems) {
    const m = map.get(item.menuItemId);
    if (!m) {
      const err = new Error(`Menu item not found: ${item.menuItemId}`);
      err.statusCode = 404;
      throw err;
    }
    if (!m.isAvailable || !m.restaurant.isActive) {
      const err = new Error("Cart contains unavailable items.");
      err.statusCode = 400;
      throw err;
    }
  }
  const created = await prisma.$transaction(async (tx) => {
    const createdOrders = [];
    for (const item of cartItems) {
      const m = map.get(item.menuItemId);
      const quantity = item.quantity;
      const totalCents = m.priceCents * quantity;
      const order = await tx.order.create({
        data: {
          customerId,
          menuItemId: m.id,
          restaurantId: m.restaurantId,
          status: OrderStatus.PENDING,
          totalCents,
          notes: input.notes ?? null,
          deliveryAddressSnapshot: input.deliveryAddressSnapshot
        }
      });
      createdOrders.push(order);
    }
    await tx.cart.update({
      where: { userId: customerId },
      data: { items: [] }
    });
    return createdOrders;
  });
  const grandTotal = created.reduce((sum, o) => sum + o.totalCents, 0);
  return {
    message: "Order placed successfully (Cash on Delivery).",
    totalCents: grandTotal,
    orderCount: created.length,
    orders: created
  };
};
var getMyOrders = async (customerId) => {
  return prisma.order.findMany({
    where: { customerId },
    include: {
      menuItem: true,
      restaurant: true
    },
    orderBy: { createdAt: "desc" }
  });
};
var getProviderOrders = async (providerId) => {
  return prisma.order.findMany({
    where: {
      restaurant: { providerId }
    },
    include: {
      menuItem: true,
      restaurant: true,
      customer: { select: { id: true, name: true, email: true, phone: true } }
    },
    orderBy: { createdAt: "desc" }
  });
};
var updateOrderStatusByProvider = async (providerId, orderId, status) => {
  const allowed = [
    OrderStatus.CONFIRMED,
    OrderStatus.PREPARING,
    OrderStatus.OUT_FOR_DELIVERY,
    OrderStatus.DELIVERED,
    OrderStatus.CANCELLED
  ];
  if (!allowed.includes(status)) {
    const err = new Error("Invalid status value.");
    err.statusCode = 400;
    throw err;
  }
  const order = await prisma.order.findFirst({
    where: {
      id: orderId,
      restaurant: { providerId }
    },
    select: { id: true, status: true }
  });
  if (!order) {
    const err = new Error("Order not found or you don't have access.");
    err.statusCode = 404;
    throw err;
  }
  if (order.status === OrderStatus.CANCELLED || order.status === OrderStatus.DELIVERED) {
    const err = new Error("This order can no longer be updated.");
    err.statusCode = 400;
    throw err;
  }
  return prisma.order.update({
    where: { id: orderId },
    data: { status }
  });
};
var orderService = {
  getallOrders,
  checkoutFromCart,
  getMyOrders,
  getProviderOrders,
  updateOrderStatusByProvider
};

// src/modules/order/order.controller.ts
var getallOrders2 = async (req, res, next) => {
  try {
    const result = await orderService.getallOrders();
    res.status(200).json(result);
  } catch (err) {
    next(err);
  }
};
var checkoutFromCart2 = async (req, res, next) => {
  try {
    const customerId = req.user.id;
    const { deliveryAddressSnapshot, notes } = req.body;
    const result = await orderService.checkoutFromCart(customerId, {
      deliveryAddressSnapshot,
      notes
    });
    res.status(201).json({
      success: true,
      ...result
    });
  } catch (err) {
    next(err);
  }
};
var getMyOrders2 = async (req, res, next) => {
  try {
    const customerId = req.user.id;
    const result = await orderService.getMyOrders(customerId);
    res.status(200).json({ success: true, data: result });
  } catch (err) {
    next(err);
  }
};
var getProviderOrders2 = async (req, res, next) => {
  try {
    const providerId = req.user.id;
    const result = await orderService.getProviderOrders(providerId);
    res.status(200).json({ success: true, data: result });
  } catch (err) {
    next(err);
  }
};
var updateOrderStatusByProvider2 = async (req, res, next) => {
  try {
    const providerId = req.user.id;
    const { orderId } = req.params;
    const { status } = req.body;
    const result = await orderService.updateOrderStatusByProvider(providerId, orderId, status);
    res.status(200).json({ success: true, data: result });
  } catch (err) {
    next(err);
  }
};
var OrderController = {
  getallOrders: getallOrders2,
  checkoutFromCart: checkoutFromCart2,
  getMyOrders: getMyOrders2,
  getProviderOrders: getProviderOrders2,
  updateOrderStatusByProvider: updateOrderStatusByProvider2
};

// src/modules/order/order.router.ts
var router4 = Router2();
router4.get("/", auth2("ADMIN" /* ADMIN */), OrderController.getallOrders);
router4.post("/checkout", auth2("CUSTOMER" /* CUSTOMER */), OrderController.checkoutFromCart);
router4.get("/me", auth2("CUSTOMER" /* CUSTOMER */), OrderController.getMyOrders);
router4.get("/provider", auth2("PROVIDER" /* PROVIDER */), OrderController.getProviderOrders);
router4.patch("/:orderId/status", auth2("PROVIDER" /* PROVIDER */), OrderController.updateOrderStatusByProvider);
var orderRouter = router4;

// src/modules/review/review.router.ts
import { Router as Router3 } from "express";

// src/modules/review/review.service.ts
var createOrUpdateReview = async (userId, data) => {
  const { menuItemId, rating, comment } = data;
  if (!menuItemId) {
    const err = new Error("menuItemId is required.");
    err.statusCode = 400;
    throw err;
  }
  if (!Number.isInteger(rating) || rating < 1 || rating > 5) {
    const err = new Error("rating must be an integer between 1 and 5.");
    err.statusCode = 400;
    throw err;
  }
  const menuItem = await prisma.menuItem.findUnique({
    where: { id: menuItemId },
    select: { id: true }
  });
  if (!menuItem) {
    const err = new Error("Menu item not found.");
    err.statusCode = 404;
    throw err;
  }
  const hasAnyOrder = await prisma.order.findFirst({
    where: {
      customerId: userId,
      menuItemId
    },
    select: { id: true }
  });
  if (!hasAnyOrder) {
    const err = new Error("You can only review items you have ordered.");
    err.statusCode = 403;
    throw err;
  }
  const review = await prisma.review.upsert({
    where: {
      userId_menuItemId: { userId, menuItemId }
    },
    create: {
      userId,
      menuItemId,
      rating,
      comment: comment ?? null
    },
    update: {
      rating,
      comment: comment ?? null
    }
  });
  return review;
};
var getReviewsByMenuItem = async (menuItemId) => {
  if (!menuItemId) {
    const err = new Error("menuItemId is required.");
    err.statusCode = 400;
    throw err;
  }
  return prisma.review.findMany({
    where: { menuItemId },
    include: {
      user: {
        select: { id: true, name: true, image: true }
      }
    },
    orderBy: { createdAt: "desc" }
  });
};
var deleteMyReview = async (userId, reviewId) => {
  if (!reviewId) {
    const err = new Error("reviewId is required.");
    err.statusCode = 400;
    throw err;
  }
  const review = await prisma.review.findFirst({
    where: { id: reviewId, userId },
    select: { id: true }
  });
  if (!review) {
    const err = new Error("Review not found or you don't have access.");
    err.statusCode = 404;
    throw err;
  }
  return prisma.review.delete({
    where: { id: reviewId }
  });
};
var reviewService = {
  createOrUpdateReview,
  getReviewsByMenuItem,
  deleteMyReview
};

// src/modules/review/review.controller.ts
var createOrUpdateReview2 = async (req, res, next) => {
  try {
    const userId = req.user.id;
    const result = await reviewService.createOrUpdateReview(userId, req.body);
    res.status(201).json({
      success: true,
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var getReviewsByMenuItem2 = async (req, res, next) => {
  try {
    const { menuItemId } = req.params;
    const result = await reviewService.getReviewsByMenuItem(menuItemId);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var deleteMyReview2 = async (req, res, next) => {
  try {
    const userId = req.user.id;
    const { reviewId } = req.params;
    const result = await reviewService.deleteMyReview(userId, reviewId);
    res.status(200).json({
      success: true,
      message: "Review deleted.",
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var ReviewController = {
  createOrUpdateReview: createOrUpdateReview2,
  getReviewsByMenuItem: getReviewsByMenuItem2,
  deleteMyReview: deleteMyReview2
};

// src/modules/review/review.router.ts
var router5 = Router3();
router5.get("/menu-item/:menuItemId", ReviewController.getReviewsByMenuItem);
router5.post("/", auth2("CUSTOMER" /* CUSTOMER */), ReviewController.createOrUpdateReview);
router5.delete("/:reviewId", auth2("CUSTOMER" /* CUSTOMER */), ReviewController.deleteMyReview);
var reviewRouter = router5;

// src/modules/user/user.router.ts
import { Router as Router4 } from "express";

// src/modules/user/user.service.ts
var ALLOWED_STATUS = ["ACTIVE", "SUSPENDED"];
var getAllUsers = async () => {
  return prisma.user.findMany({
    where: {
      role: {
        in: ["CUSTOMER", "PROVIDER"]
      }
    },
    select: {
      id: true,
      name: true,
      email: true,
      emailVerified: true,
      role: true,
      phone: true,
      status: true,
      businessName: true,
      isApproved: true,
      createdAt: true
    },
    orderBy: {
      createdAt: "desc"
    }
  });
};
var updateUserStatus = async (userId, status) => {
  if (!userId) {
    const err = new Error("userId is required.");
    err.statusCode = 400;
    throw err;
  }
  if (typeof status !== "string" || !ALLOWED_STATUS.includes(status)) {
    const err = new Error(`Invalid status. Allowed: ${ALLOWED_STATUS.join(", ")}`);
    err.statusCode = 400;
    throw err;
  }
  const userExists = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true, role: true }
  });
  if (!userExists) {
    const err = new Error("User not found.");
    err.statusCode = 404;
    throw err;
  }
  if (userExists.role === "ADMIN") {
    const err = new Error("Cannot suspend an admin.");
    err.statusCode = 403;
    throw err;
  }
  return prisma.user.update({
    where: { id: userId },
    data: { status },
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true,
      updatedAt: true
    }
  });
};
var updateMe = async (userId, data) => {
  const allowedData = {};
  if (data.name !== void 0) allowedData.name = data.name;
  if (data.phone !== void 0) allowedData.phone = data.phone;
  if (data.image !== void 0) allowedData.image = data.image;
  if (data.addresses !== void 0) allowedData.addresses = data.addresses;
  if (data.businessName !== void 0) allowedData.businessName = data.businessName;
  if (Object.keys(allowedData).length === 0) {
    const err = new Error("No valid fields provided for update.");
    err.statusCode = 400;
    throw err;
  }
  return prisma.user.update({
    where: { id: userId },
    data: allowedData,
    select: {
      id: true,
      name: true,
      email: true,
      phone: true,
      image: true,
      addresses: true,
      businessName: true,
      role: true,
      status: true,
      createdAt: true,
      updatedAt: true
    }
  });
};
var getMe = async (userId) => {
  return prisma.user.findUnique({
    where: { id: userId },
    select: {
      id: true,
      name: true,
      email: true,
      phone: true,
      image: true,
      addresses: true,
      businessName: true,
      role: true,
      status: true,
      createdAt: true,
      updatedAt: true
    }
  });
};
var userService = {
  getAllUsers,
  updateUserStatus,
  updateMe,
  getMe
};

// src/modules/user/user.controller.ts
var getAllUsers2 = async (req, res, next) => {
  try {
    const result = await userService.getAllUsers();
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var updateUserStatus2 = async (req, res, next) => {
  try {
    const { userId } = req.params;
    const { status } = req.body;
    const result = await userService.updateUserStatus(userId, status);
    res.status(200).json({
      success: true,
      message: "User status updated.",
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var updateMe2 = async (req, res, next) => {
  try {
    const userId = req.user.id;
    const result = await userService.updateMe(userId, req.body);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var getMe2 = async (req, res, next) => {
  try {
    const userId = req.user.id;
    const result = await userService.getMe(userId);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (err) {
    next(err);
  }
};
var UserController = {
  getAllUsers: getAllUsers2,
  updateUserStatus: updateUserStatus2,
  updateMe: updateMe2,
  getMe: getMe2
};

// src/modules/user/user.router.ts
var router6 = Router4();
router6.get("/", auth2("ADMIN" /* ADMIN */), UserController.getAllUsers);
router6.get("/me", auth2(), UserController.getMe);
router6.patch("/me", auth2(), UserController.updateMe);
router6.patch("/:userId/status", auth2("ADMIN" /* ADMIN */), UserController.updateUserStatus);
var userRouter = router6;

// src/app.ts
var app = express3();
app.use(express3.json());
var allowedOrigins = [
  process.env.APP_URL || "http://localhost:3000",
  process.env.PROD_APP_URL,
  process.env.FRONTEND_URL
].filter(Boolean);
app.use(
  cors({
    origin: (origin, callback) => {
      if (!origin) return callback(null, true);
      const isAllowed = allowedOrigins.includes(origin) || /^https:\/\/.*\.vercel\.app$/.test(origin) || origin === "http://localhost:3000" || origin === "http://localhost:3001";
      if (isAllowed) {
        callback(null, true);
      } else {
        callback(new Error(`Origin ${origin} not allowed by CORS`));
      }
    },
    credentials: true,
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization", "Cookie"],
    exposedHeaders: ["Set-Cookie"]
    // maxAge: 86400, // 24 hours
  })
);
app.all("/api/auth/{*any}", toNodeHandler(auth));
app.use("/menu-items", menuItemsRouter);
app.use("/restaurants", restaurantRouter);
app.use("/cart", cartRouter);
app.use("/orders", orderRouter);
app.use("/reviews", reviewRouter);
app.use("/users", userRouter);
app.use(globalErrorEandler_default);

// src/index.ts
var index_default = app;
export {
  index_default as default
};
